### ISSUE TITLE
[Ingest] Observation bias correction files for the golden month using the new convention

### ISSUE THREAD

**Issue by fabiolrdiniz** [JCSDA-internal/r2d2-ingest#10]
## Ingest description
Using the new convention, we need to ingest observation bias correction files for the golden month.

These files are being converted and will be stored on orion.

For the sake of simplicity, we are going to store all the files under:

- provider: noaa
- experiment: oper
- model: gfs

## Date range

Start date: 2022-02-13T18:00:00Z

End date: 2022-03-14T18:00:00Z

## Source host and directory/bucket

Source host: orion

Data store directory path or S3 bucket path (_with wildcards if needed_): `/work2/noaa/da/fdiniz/4Eric`

## Target data store type (select one)

- [x] archive
- [ ] experiments
- [ ] gfs ensemble
- [ ] other 
    - Please describe: 

## Data store checklist

Data copied into R2D2 on:

- [x] Cheyenne
- [x] Discover
- [x] Orion
- [x] S3 (us-east-1)
- [x] S3 (us-east-2)
- [x] S4

## Associated pull request in [r2d2/scripts](https://github.com/JCSDA-internal/r2d2/tree/develop/scripts) (if creating new ingestion scripts)

*(This instruction will change once we create the r2d2-ingest repository.)*

**Comment by ericlingerfelt** [comment]
In progress on Orion.
