### ISSUE TITLE
update atmosphere r2d2 ingest to single script and series of yaml

### ISSUE THREAD

**Issue by BenjaminRuston** [JCSDA-internal/r2d2-ingest#11]
## Description

likely still need a large think about reorganization of this structure but would like to move all observations into a single bucket called `obs` maybe have components under that, but in the longer term plans these observation should be able to be used by multiple components

update script to put atmospheric observation into r2d2 archive

## Acceptance Criteria (Definition of Done)

observation ioda files can be ingested into r2d2

**Comment by ericlingerfelt** [comment]
Any updates on this issue? Thanks!

**Comment by BenjaminRuston** [comment]
my impression @ericlingerfelt is another discussion with Eric, Ashley and Fabio and create a new issue,, oh and Jerome and Travis too but think we are in a better position now to define our way forward

I do not think this should be a part of the technical debt let that clear then this is subsequent
