### ISSUE TITLE
[Bug] [Ingest] Empty files cannot contain Channels defined

### ISSUE THREAD

**Issue by fabiolrdiniz** [JCSDA-internal/r2d2-ingest#13]
## Current behavior (describe the bug)
With the merge of https://github.com/JCSDA-internal/ioda/pull/946 into the release branch, the empty files stored in r2d2 should not contain the `Channels` variable defined in it, otherwise, the experiment will crash with the code as it is now.

A possible workaround is to harvest the database searching for empty files and temporarily replace them with the files that JEDI is capable to handle (as the code is right now):

```
netcdf empty_obs_file {
dimensions:
	Location = UNLIMITED ; // (0 currently)
}
```

## To Reproduce
One of the many possible cases is the skylab-atm-land experiment running for the `2022-02-15T12:00:00Z` cycle when using ABI G17.

## Expected behavior
The database shouldn't have empty files, that was a workaround for v3, and it's going to be again a workaround for v4. In the long run, we should remove these files and let r2d2 return them to the user.

## Target data store type (select one)

- [x] archive
- [ ] experiments
- [ ] gfs ensemble
- [ ] other 
    - Please describe: 

## Data store checklist

Data copied into R2D2 on:

- [x] Cheyenne
- [x] Discover
- [x] Orion
- [x] S3 (us-east-1)
- [x] S3 (us-east-2)
- [x] S4

**Comment by ericlingerfelt** [comment]
Hi @fabiolrdiniz, I can take it from here. Thanks!

**Comment by fabiolrdiniz** [comment]
Thanks for saying @climbfuji. Exactly that. If you dump the `abi_g17_bt_64km` file (probably inside `tmp/ewok/EXPID/2022-02-15T12:00:00Z/obs/obs.abi_g17_bt_64km.2022-02-15T12:00:00Z.nc4`), you will notice that the file contains `Location=0`.

**Comment by climbfuji** [comment]
> Thanks for saying @climbfuji. Exactly that. If you dump the `abi_g17_bt_64km` file (probably inside `tmp/ewok/EXPID/2022-02-15T12:00:00Z/obs/obs.abi_g17_bt_64km.2022-02-15T12:00:00Z.nc4`), you will notice that the file contains `Location=0`.

Thanks! Happy to hear that. Will wait for any further runs of skylab-atm-land until this is fixed.

**Comment by ericlingerfelt** [comment]
Hi @fabiolrdiniz, I just completed this replacement using `r2d2-archive-orion`. Please test your experiment on Orion.

**Comment by fabiolrdiniz** [comment]
Hi, @ericlingerfelt. I was able to finish the cycle for `2022-02-15T12:00:00Z` using `abi_g17_bt_64km`. But I had to add a piece of code in the ensemble mean & std. dev. calculation as it's in https://github.com/JCSDA-internal/SIMOBS/pull/81.

**Comment by climbfuji** [comment]
So are we ever going to have a code ready for release/skylab-v4?

@fabiolrdiniz Can you please let me know which lines do I need to add in simobs to make this work? We should have a tiny bug fix PR for simobs for release/skylab-v4 instead of 81 that fixes only what's needed. Thanks ...

**Comment by climbfuji** [comment]
Oh so I see you want the entire PR 81 go in? Wow. Alright, I'll approve, merge and then see if it works on AWS.

@ericlingerfelt Can you update the us-east-1/2 S3 buckets please?

**Comment by fabiolrdiniz** [comment]
> So are we ever going to have a code ready for release/skylab-v4?

Thanks for your patience, @climbfuji. Unfortunately, I don't know how to answer your question. We fix one thing and another issue appears. I'm trying to anticipate the crashes that you are going to get when running the experiment. Nobody really ran what is being assembled in release/skylab-v4 as it is now. I really hope things will run smoothly.

**Comment by climbfuji** [comment]
> > So are we ever going to have a code ready for release/skylab-v4?
> 
> Thanks for your patience, @climbfuji. Unfortunately, I don't know how to answer your question. We fix one thing and another issue appears. I'm trying to anticipate the crashes that you are going to get when running the experiment. Nobody really ran what is being assembled in release/skylab-v4 as it is now. I really hope things will run smoothly.

Me too :-)

**Comment by ericlingerfelt** [comment]
Please let me know if you need anything from me.

**Comment by fabiolrdiniz** [comment]
> Please let me know if you need anything from me.

Same here.

**Comment by climbfuji** [comment]
@fabiolrdiniz @ericlingerfelt After uploading the fixed observation data to the us-east-2 bucket, I am still getting this failure in cycle=2 of skylab-atm-land: `Bad parameter: Selected channel number 7 does not exist caught in ...`

@ericlingerfelt Are we sure the parallel cluster gets its data from the us-east-2 bucket? I am updating the us-east-1 data now. Then I will try to rerun the entire cycle and see what happens (hopefully it will re-download the data and not just use what is already there, not sure how to check - @cmgas?)

**Comment by ericlingerfelt** [comment]
(1) After looking at the `data_store` table, `us-east-1` will be accessed by `aws-pcluster` first when that table is queried. 
(2) It probably still won't work since https://github.com/JCSDA-internal/r2d2/pull/368 was not merged into the release. At this time, no `host` can download data from S3. 
(3) If we had created a local data store called `r2d2-archive-aws-pcluster` like the other hosts, this issue would not happen at this time. 
(4) This is a symptom of https://github.com/JCSDA-internal/r2d2/issues/366.

What to do next? These two steps.

(1) Merge the `release` into `develop` and merge https://github.com/JCSDA-internal/r2d2/pull/368 into `develop` and use `develop` for the run. 
(2) I will modify the `data_store` table so that the `aws-pcluster` uses `us-east-2`.

**Comment by ericlingerfelt** [comment]
I have modified the `data_store` table so that the `aws-pcluster` will only use `us-east-2`. Please try again.

**Comment by climbfuji** [comment]
> I have modified the `data_store` table so that the `aws-pcluster` will only use `us-east-2`. Please try again.

I will do that, thanks.

I don't think that the following is true "(2) that no host can download data from S3, but the aws-pcluster may be different since you are mounting the bucket." We are not mounting the bucket and aws-pcluster downloaded the data just fine (albeit from the wrong data store).

**Comment by ericlingerfelt** [comment]
You are correct. After looking at the code, "(2) that no host can download data from S3" applies to the HPC hosts and not `aws-pcluster`.

**Comment by climbfuji** [comment]
Thanks @ericlingerfelt. I will run a test experiment for the offending cycle and only three members first before I kick off the full experiment from the beginning.

**Comment by ericlingerfelt** [comment]
@climbfuji, All syncs are complete except for Discover.
