### ISSUE TITLE
[Ingest] Updated GOES16/17 files with correct solar angles and integer PreQC variable

### ISSUE THREAD

**Issue by gthompsnJCSDA** [JCSDA-internal/r2d2-ingest#14]
## Ingest description

As per [ioda-converters issue 1208](https://github.com/JCSDA-internal/ioda-converters/issues/1208), the solar angles code has been corrected and the 2 golden months of data have been reprocessed (at 64km subsampling).  Also, `sensorAzimuthAngle ` and `sensorViewAngle` have been corrected as well.

Description: 

GOES16/17 (ABI) data, infrared (channels 7-16) and visible (channels 1-6), each set is contained in a separate file.  Original provider is NOAA.  Data are observations at 3-hour intervals (except some missing times especially for GOES-17).

## Date range

Start date:  2021-07-31T00:00:00Z
End date: 2021-08-31T21:00:00Z

and

Start date:  2022-02-14T00:00:00Z
End date: 2022-03-15T21:00:00Z

## Source host and directory/bucket

Source host:  AWS, S3

  s3://greg-jcsda-tmp/data/g1?_64km_ch??-??_202[12]*.nc

## Target data store type (select one)

- [x] archive
- [ ] experiments
- [ ] gfs ensemble
- [ ] other 
    - Please describe: 

## Data store checklist

Data copied into R2D2 on:

- [x] Cheyenne
- [x] Discover
- [x] Orion 
- [x] S3 (us-east-1)
- [x] S3 (us-east-2)
- [x] S4

**Comment by gthompsnJCSDA** [comment]
**DRAFT**  Setting this issue as draft for right now, because another fix was made, this time to `sensorAzimuthAngle` and the S3 bucket of data is being updated by the code in [ioda-converters PR 1230](https://github.com/JCSDA-internal/ioda-converters/pull/1230).  I will comment again when both golden months are reprocessed.

**Comment by gthompsnJCSDA** [comment]
@ericlingerfelt   The reprocessing has completed.  The S3 bucket contains all new files and everything should be ready to go for the R2D2 archive now.

**Comment by ericlingerfelt** [comment]
Hi @gthompsnJCSDA, I am working on this data ingest today. Thanks!

**Comment by ericlingerfelt** [comment]
Hi @gthompsnJCSDA, we use `bt` for `ch01-06`. What do we want to use for `ch07-16`? `ir`?

**Comment by ericlingerfelt** [comment]
Or is it the reverse?

**Comment by gthompsnJCSDA** [comment]
It's the reverse.  Channels 1-6 are visible reflectance/albedo and channels 7-16 are infrared brightnessTemperature

**Comment by ericlingerfelt** [comment]
OK. Thanks! What is the abbreviation for reflectance/albedo? `rf` ?

**Comment by ericlingerfelt** [comment]
```
    observation_type = input_file_name[0:16]
    if observation_type == 'g16_64km_ch01-06':
        observation_type = 'abi_g16_rf_64km'
    elif observation_type == 'g16_64km_ch07-16':
        observation_type = 'abi_g16_bt_64km'
    elif observation_type == 'g17_64km_ch01-06':
        observation_type = 'abi_g17_rf_64km'
    elif observation_type == 'g17_64km_ch07-16':
        observation_type = 'abi_g17_bt_64km'
```

**Comment by ericlingerfelt** [comment]
It is part of the `observation_type`.

**Comment by ericlingerfelt** [comment]
The observation_type is used on the UFO yamls to find this data (I think).

**Comment by ericlingerfelt** [comment]
Hi @gthompsnJCSDA, I completed this ingest job over the weekend, but unfortunately, the extension of the original file set was 'nc4' and the extension used with this file set is 'nc'. Therefore, we now have two copies of the GOES data in R2D2. I assumed that the file extension was the same as before and failed to check the new file set's value. I will have to manually remove the 'nc4' files from before we can call this closed. I don't currently know how long that will take.

**Comment by gthompsnJCSDA** [comment]
Thanks Eric.  I have no idea how the orig file ended with `.nc4` because I dislike this extension as we could just as easily get rid of the 4 forever - so I pretty much don't use it.  Sorry for the added step to delete old files.

**Comment by ericlingerfelt** [comment]
What I am going to do for now is delete the nc extension ones and re-store these as the nc4 ones since that extension has already been used in all of the archives and the database for g16/17.

**Comment by gthompsnJCSDA** [comment]
> What I am going to do for now is delete the nc extension ones and re-store these as the nc4 ones since that extension has already been used in all of the archives and the database for g16/17.


Can I get a double-check on this?  Why **delete** the new ones?  Do you just mean you plan to rename my new files currently ending in `.nc` into the older names with `.nc4`?  I would hate to see my work thrown out.  I fixed things in the files.

**Comment by ericlingerfelt** [comment]
I am not deleting your work. It is just simpler for me to delete the new files and re-store them as nc4.

**Comment by gthompsnJCSDA** [comment]
> I am not deleting your work. It is just simpler for me to delete the new files and re-store them as nc4.

Hence my question. It's a bit confusing to read as to the actual solution.  Ambiguous word: "these."

**Comment by ericlingerfelt** [comment]
This is back in progress.

**Comment by ericlingerfelt** [comment]
Completed on Orion using `nc4`.

**Comment by gthompsnJCSDA** [comment]
@ericlingerfelt   If my original files are already on S3, is it pretty simple for you to copy/move them from my S3 bucket into the one for R2D2 usage?  And I would assume a renaming would be needed there to end the filenames in `.nc4` as well right?

**Comment by ericlingerfelt** [comment]
Done.
