### ISSUE TITLE
[Ingest] Re-ingest of all trace gas data 

### ISSUE THREAD

**Issue by ericlingerfelt** [JCSDA-internal/r2d2-ingest#15]
## Ingest description

All trace gas data in R2D2 must be upgraded and re-ingested. 

Description: skylab trace gas observations

Data type: Observation

Other metadata (_For example, provider, observation type, model_): 

window length for all obs: PT6H

- observation type: tropomi_s5p_co_total 
  provider: esa
  window_start range: 20210801T06 - 20210831T18
  file extension: nc4

- observation type: tropomi_s5p_no2_total
  provider: esa
  window_start range: 20210801T00 - 20210810T00
  file extension: nc4

- observation type: tropomi_s5p_no2_tropo
  provider: esa
  window_start range: 20210801T00 - 20210810T00
  file extension: nc4

- observation type: mopitt_terra_co
  provider: nasa
  window_start range: 20210801T00 - 20210810T00
  file extension: nc4

## Source host and directory/bucket

Source host: Orion

Data store directory path or S3 bucket path (_with wildcards if needed_):
/work/noaa/da/barre/upgrade_trace_gas/upgraded

## Target data store type (select one)

- [x] archive
- [ ] experiments
- [ ] gfs ensemble
- [ ] other 
    - Please describe: 

## Data store checklist

Data copied into R2D2 on:

- [x] Cheyenne
- [x] Discover
- [x] Orion
- [x] S3 (us-east-1)
- [x] S3 (us-east-2)
- [x] S4

**Comment by ericlingerfelt** [comment]
Hi @jeromebarre, The next time you timestamp your files, do you care to use `window_start` and not `window_center`? That is, subtract `PT3H` from the date. I just noticed this while ingesting your files and now I have to back up and clean up the database. Thanks!

**Comment by ericlingerfelt** [comment]
Hi @jeromebarre, Did you already ingest this data into r2d2-experiments-orion or some other R2D2 data store?

**Comment by jeromebarre** [comment]
Yes it's on `r2d2-experiment-orion`

**Comment by ericlingerfelt** [comment]
Great! Thanks! Have a great weekend.

**Comment by ericlingerfelt** [comment]
Hi @mer-a-o, Hopefully by Wed COB, but that depends on the needs of next week's demo which has been prioritized. What level of need do you have for this to be completed?

**Comment by mer-a-o** [comment]
Thanks @ericlingerfelt. I need to run some trace gas experiments for my talk at the workshop next Thursday. Right now trace gas experiments are broken because of this change in obs format.

**Comment by ericlingerfelt** [comment]
Hi @mer-a-o, OK. I'll move you up the ladder too!

**Comment by mer-a-o** [comment]
@ericlingerfelt Thank you!!

**Comment by ericlingerfelt** [comment]
@mer-a-o, What platform are you testing on?

**Comment by mer-a-o** [comment]
@ericlingerfelt Orion and S4.

**Comment by ericlingerfelt** [comment]
I'm staging everything in r2d2-archive-orion to start with before syncing. So let's go with Orion for now.

**Comment by mer-a-o** [comment]
Sounds good.

**Comment by ericlingerfelt** [comment]
HI @mer-a-o, You can still use the data files in `r2d2-experiments-orion`. All you need to do is add `data_store='r2d2-experiments-orion'` to your `store` and `fetch` calls.

**Comment by ericlingerfelt** [comment]
Are these the same files in `/work/noaa/da/barre/upgrade_trace_gas/upgraded`?

**Comment by jeromebarre** [comment]
yes

**Comment by ericlingerfelt** [comment]
This is back in progress on Orion.

**Comment by ericlingerfelt** [comment]
Complete on Orion.

**Comment by mer-a-o** [comment]
Hi @ericlingerfelt. Do you have an estimate on when the new obs will be available on Discover and S4? Thanks.

**Comment by climbfuji** [comment]
I will work with him on transferring the data - thanks for the reminder

**Comment by mer-a-o** [comment]
@climbfuji Thanks!

**Comment by ericlingerfelt** [comment]
Hi All - I still need to remove the c12 ens oper backgrounds from r2d2-archive-orion that were mistakenly created by ALGO prior to the demo before we can sync. See https://github.com/JCSDA-internal/r2d2-ingest/issues/29.

**Comment by ericlingerfelt** [comment]
Done.
