### ISSUE TITLE
[Ingest] Create and ingest the sample of files needed for h(x) simulation during 14-16 Feb 2023

### ISSUE THREAD

**Issue by fabiolrdiniz** [JCSDA-internal/r2d2-ingest#17]
## Ingest description
This issue has been created to document the creation of the sample of files needed for h(x) simulation during 14-16 Feb 2023. Files created here are expected to be ingested in the archive after testing.

## Date range

Start date: 14 Feb 2023

End date: 16 Feb 2023

## Source host and directory/bucket

Source host: orion

Data store directory path or S3 bucket path (_with wildcards if needed_): shared r2d2 on orion

## Target data store type (select one)

- [x] archive
- [ ] experiments
- [ ] gfs ensemble
- [ ] other 
    - Please describe: 

## Data store checklist

Data copied into R2D2 on:

- [ ] Cheyenne
- [ ] Discover
- [ ] Orion
- [ ] S3 (us-east-1)
- [ ] S3 (us-east-2)
- [ ] S4

## Associated pull request in [r2d2/scripts](https://github.com/JCSDA-internal/r2d2/tree/develop/scripts) (if creating new ingestion scripts)
None

**Comment by fabiolrdiniz** [comment]
@BenjaminRuston, please, can you add the correct Epic here?

**Comment by BenjaminRuston** [comment]
@fabiolrdiniz these will only need to go to the archive if we decide to run these test on other platforms besides Orion

we're still in the situation where sponsors request on off testing

**Comment by fabiolrdiniz** [comment]
Thanks, @BenjaminRuston! That's important information. So no need to sync r2d2 across the platforms.

**Comment by BenjaminRuston** [comment]
I would think so, but is good to record the work in generating the files so having the issue is not a bad plan to record this

**Comment by fabiolrdiniz** [comment]
Observations during Feb 2023 for:

- `gnssro`: `/work2/noaa/da/bruston/data_repos/ioda/gnssro/202302??T??Z_PT6H_gnssro.nc4`
- `gnssro_noaa_comm`: `/work2/noaa/da/bruston/data_repos/ioda/gnssro/202302??T??Z_PT6H_gnssro_noaa_comm.nc4`
- `gnssro_spire`: `/work2/noaa/da/bruston/data_repos/ioda/gnssro/202302??T??Z_PT6H_gnssro_spire.nc4`

were stored in the `r2d2-experiments` on Orion. As well as background files at the c768 resolution from GFS (`/work2/noaa/da/bruston/jedi/fv3/restart/gdas.202302??/??/atmos/RESTART`). These files allow one to easily run a variety of experiments (such h(x) or 3d-Var). An example of a 3d-Var run is presented below, using backgrounds at c768 and minimization at c384:

- observation counts:
<img src="https://user-images.githubusercontent.com/45880035/236919015-a1c6222b-0e23-4970-bd62-e0faba8b0781.png" width=50% height=50%>

- total impacts:
<img src="https://user-images.githubusercontent.com/45880035/236919104-fa7ccb2b-8713-4d44-89e2-a8a8d0ab4be0.png" width=50% height=50%>

- impact per obs:
<img src="https://user-images.githubusercontent.com/45880035/236920209-43377489-80a1-48c1-9fbf-33b5e525135e.png" width=50% height=50%>

**Comment by ericlingerfelt** [comment]
This issue appears to include ingestion of this data to r2d2-archive. I am reopening now.

**Comment by fabiolrdiniz** [comment]
Sorry for the confusion, @ericlingerfelt. I thought the same, but @BenjaminRuston said that there is no need for that (please see https://github.com/JCSDA-internal/r2d2-ingest/issues/17#issuecomment-1533706908). Files inside `r2d2-experiments` would be sufficient for it. No need to have files spread across platforms.

**Comment by ericlingerfelt** [comment]
Hi @fabiolrdiniz, Thank you for the additional information. In this case, this issue should not be an ingest issue. The way the current issue is created, it is expected for INFRA to ingest into archive all of these files into the data stores listed in Data store checklist. I will update this issue.

**Comment by BenjaminRuston** [comment]
thanks @ericlingerfelt and @fabiolrdiniz , yes in the future we will maybe put this as a ufo issue?  but we basically need somewhere to track the work we are being asked to do by our sponsors.

these can be one-off studies of new instruments and sensors such as this one

**Comment by BenjaminRuston** [comment]
new spire receivers:
![gnssro commercial bendingAngle ob 2023021612](https://github.com/JCSDA-internal/r2d2-ingest/assets/93737224/d97e12a4-fda5-4b63-a130-2cf385410228)


OmB or bending angle fit to background for new recievers:
![gnssro commercial bendingAngle profile 2023021612](https://github.com/JCSDA-internal/r2d2-ingest/assets/93737224/cb6d4363-96a4-4a7a-b042-acc6e7e4a041)
