### ISSUE TITLE
[Ingest] put it any available aircraft prepbufr for feb2022 test period

### ISSUE THREAD

**Issue by BenjaminRuston** [JCSDA-internal/r2d2-ingest#20]
## Ingest description

Data type (_For example, observation, forecast_):
observation data from aircraft
these are processed by NOAA NCO and put into prepBUFR files.  the 48h latent have 250K these only contain roughly 2.5k observations so miss restricted data but a whole lot more as well

## Date range

Start date:   20220221T03Z

End date:  20220225T09Z

## Source host and directory/bucket

Source host: Orion

6944: 20220221T03Z_PT6H_aircraft_prepbufr.nc4
9436: 20220221T09Z_PT6H_aircraft_prepbufr.nc4
5921: 20220221T15Z_PT6H_aircraft_prepbufr.nc4
9402: 20220221T21Z_PT6H_aircraft_prepbufr.nc4
10463: 20220222T03Z_PT6H_aircraft_prepbufr.nc4
6623: 20220222T09Z_PT6H_aircraft_prepbufr.nc4
4817: 20220222T15Z_PT6H_aircraft_prepbufr.nc4
11028: 20220222T21Z_PT6H_aircraft_prepbufr.nc4
4418: 20220223T03Z_PT6H_aircraft_prepbufr.nc4
6420: 20220223T09Z_PT6H_aircraft_prepbufr.nc4
4944: 20220223T15Z_PT6H_aircraft_prepbufr.nc4
5464: 20220223T21Z_PT6H_aircraft_prepbufr.nc4
5227: 20220224T03Z_PT6H_aircraft_prepbufr.nc4
6826: 20220224T09Z_PT6H_aircraft_prepbufr.nc4
9279: 20220224T15Z_PT6H_aircraft_prepbufr.nc4
4676: 20220224T21Z_PT6H_aircraft_prepbufr.nc4
5415: 20220225T03Z_PT6H_aircraft_prepbufr.nc4
5093: 20220225T09Z_PT6H_aircraft_prepbufr.nc4

## Target data store type (select one)

- [x] archive
- [ ] experiments
- [ ] gfs ensemble
- [ ] other 
    - Please describe: 

## Data store checklist

Data copied into R2D2 on:

- [x] Cheyenne
- [x] Discover
- [x] Orion
- [x] S3 (us-east-1)
- [x] S3 (us-east-2)
- [x] S4

## Associated pull request in [r2d2/scripts](https://github.com/JCSDA-internal/r2d2/tree/develop/scripts) (if creating new ingestion scripts)

*(This instruction will change once we create the r2d2-ingest repository.)*

**Comment by ericlingerfelt** [comment]
I am assuming that these have been ingested into `r2d2-experiments-orion`, yes? These are the exact indices you want moved from `r2d2-experiments-orion` and into all `r2d2-archives`?

**Comment by ericlingerfelt** [comment]
Are these ready and do you need these for the demos next week?

**Comment by BenjaminRuston** [comment]
these are ready, and @fabiolrdiniz can confirm but do not think these dates are being used either for the demo next week

**Comment by fabiolrdiniz** [comment]
Thanks for checking, @BenjaminRuston! No, these dates are not being used in the demo.

**Comment by ericlingerfelt** [comment]
Well, Orion just went down. I though we were going to stop using Orion for ingest staging? In the future, we should use AWS.

**Comment by ericlingerfelt** [comment]
Back on login 2.

**Comment by ericlingerfelt** [comment]
This data existed in archive previously correct? We are now overwriting existing data?

**Comment by fabiolrdiniz** [comment]
Yes. It existed in the database as a valid empty file:

```
dimensions:
	Location = UNLIMITED ; // (0 currently)
}
```

**Comment by ericlingerfelt** [comment]
Done on Orion.

**Comment by fabiolrdiniz** [comment]
The `skylab-atm-land` experiment passed cycle 25 with the new file (not empty anymore). There were others during the period though.

**Comment by ericlingerfelt** [comment]
Done except for S4. (It's slow)
