### ISSUE TITLE
[Ingest] c12 gfs ensemble backgrounds

### ISSUE THREAD

**Issue by cmgas** [JCSDA-internal/r2d2-ingest#21]
## Ingest description

Data type: forecast
Other metadata: gfs
Members: 0-19
Resolution: c12

## Date range

Start date: 2022-02-14T18:00:00Z
End date: 2022-02-18T18:00:00Z
Step: PT6H

## Source host and directory/bucket

Source host: currently on Orion in the experiments DB with the expid: 3fbcd8

## Target data store type (select one)

- [ ] archive
- [ ] experiments
- [x] gfs ensemble
- [ ] other 
    - Please describe: 

## Data store checklist

Data copied into R2D2 on:

- [x] Cheyenne
- [x] Discover
- [x] Orion
- [ ] S3 (us-east-1) [DOUBLE CHECK]
- [ ] S3 (us-east-2) [DOUBLE CHECK]
- [x] S4

**Comment by ericlingerfelt** [comment]
Thank you!

**Comment by ericlingerfelt** [comment]
In progress on Orion.

**Comment by ericlingerfelt** [comment]
FYI - There are 8500 files to be processed in this issue. That may take 2-3 days on Orion. I'm shepherding.

**Comment by ericlingerfelt** [comment]
Still in progress on Orion.

**Comment by ericlingerfelt** [comment]
Still in progress on Orion.

**Comment by ericlingerfelt** [comment]
Complete on Orion. Experiment is now 'oper'.

**Comment by ericlingerfelt** [comment]
This is not complete. We missed some files to move.

**Comment by ericlingerfelt** [comment]
Script to complete move is underway.

**Comment by ericlingerfelt** [comment]
Done.
