### ISSUE TITLE
[Ingest] c24 deterministic background

### ISSUE THREAD

**Issue by cmgas** [JCSDA-internal/r2d2-ingest#22]
## Ingest description

Data type: forecast
Other metadata: gfs
Resolution: c24

## Date range

Start date: 2022-02-14T18:00:00Z
End date: 2022-02-18T18:00:00Z
Step: PT6H

## Source host and directory/bucket

Source host: currently on Orion in the experiments DB with the expid: b83c4b

## Target data store type (select one)

With the other deterministic backgrounds, is that archive?

## Data store checklist [IN ARCHIVE]

Data copied into R2D2 on:

- [x] Cheyenne
- [x] Discover
- [x] Orion
- [x] S3 (us-east-1)
- [x] S3 (us-east-2)
- [x] S4

**Comment by ericlingerfelt** [comment]
In progress on Orion.

**Comment by ericlingerfelt** [comment]
Complete on Orion.

**Comment by ericlingerfelt** [comment]
These are now under experiment='oper'.

**Comment by ericlingerfelt** [comment]
Done.
