### ISSUE TITLE
[Ingest] new observations and static files for Skylab v5

### ISSUE THREAD

**Issue by BenjaminRuston** [JCSDA-internal/r2d2-ingest#34]
## Ingest description

ingest new observations at this time SSMIS over the Aug2021 and Feb2022 study period

Description: 

observation

observation type
SSMIS

## Date range

Start date: 01Aug2021 00Z; 15Feb2022 00Z

End date: 01Sep2021 00Z; 15Mar2022

## Source host and directory/bucket

Source host: Orion (r2d2-experiments-orion)

Data store directory path or S3 bucket path (_with wildcards if needed_):
/work2/noaa/da/jedipara/r2d2-experiments-orion/observation/202{108,20[2-3]}T*Z/[0-9]*.nc4

## Target data store type (select one)

- [x] archive
- [ ] experiments
- [ ] gfs ensemble
- [ ] other 
    - Please describe: 

## Data store checklist

Data copied into R2D2 on:

- [x] Cheyenne
- [x] Discover
- [x] Orion
- [x] S3 (us-east-1)
- [x] S3 (us-east-2)
- [x] S4

## Associated pull request in [r2d2/scripts](https://github.com/JCSDA-internal/r2d2/tree/develop/scripts) (if creating new ingestion scripts)

*(This instruction will change once we create the r2d2-ingest repository.)*

**Comment by BenjaminRuston** [comment]
@fabiolrdiniz please add details on bias coefficients here.

if you'd like to open a separate issue, please just let me know and we'll proceed either way

**Comment by BenjaminRuston** [comment]
log file from r2d2 store command:

[ssmis_Feb2022_r2d2_store.log](https://github.com/JCSDA-internal/r2d2-ingest/files/11691298/ssmis_Feb2022_r2d2_store.log)

**Comment by ericlingerfelt** [comment]
Please add a separate issue for the bias correction files. Please ingest these new files into an r2d2-experiments data store with a unique provider for identification of the entire set. Once these files have been ingested into an r2d2-experiments data store and tested in Skylab, we will move these files to the archive with the correct provider. Thanks!

**Comment by ericlingerfelt** [comment]
Are we ingesting both time periods here or just Feb-Mar? @ytremolet said that we were only doing Feb-Mar for the release.

**Comment by ericlingerfelt** [comment]
Feb-Mar in progress on Orion.

**Comment by ericlingerfelt** [comment]
Done for Feb-Mar on Orion.

**Comment by BenjaminRuston** [comment]
it is best to do both would think otherwise it's just a task lying around. would roll with the momentum

**Comment by ericlingerfelt** [comment]
> it is best to do both would think otherwise it's just a task lying around. would roll with the momentum.

I have very limited time before I go on vacation tomorrow. Any task that can wait would be good for me. Please talk to @ytremolet and the Aug time period if it is required for the release.

**Comment by ericlingerfelt** [comment]
The Aug time periods will be completed next week.

**Comment by ericlingerfelt** [comment]
Done except for S4.

**Comment by ericlingerfelt** [comment]
Aug in progress.

**Comment by ericlingerfelt** [comment]
Checking S4.

**Comment by ericlingerfelt** [comment]
S4 checked for Feb. Aug is done on Orion.
