### ISSUE TITLE
[Ingest] Removal of all data files not associated with both Golden Time Periods

### ISSUE THREAD

**Issue by ericlingerfelt** [JCSDA-internal/r2d2-ingest#4]
## Ingest description

Description: This issue addresses the need to remove all data files not associated with with the Golden Time Periods of Aug 2021 and Feb/Mar 2022 from all archives. 

Data type: All

Other metadata: All

## Date range

Start date: All 

End date: All

## Target data store type (select one)

- [x] archive
- [ ] experiments
- [ ] gfs ensemble
- [ ] other 
    - Please describe: 

## Data store checklist

Data removed from R2D2 on:

- [ ] Cheyenne
- [ ] Discover
- [ ] Orion
- [ ] S3 (us-east-1)
- [ ] S3 (us-east-2)
- [ ] S4

## Associated issues

https://github.com/JCSDA-internal/r2d2-data/issues/35

**Comment by ericlingerfelt** [comment]
@climbfuji, I will complete as many steps as I can before handing off to you.

**Comment by climbfuji** [comment]
I think the time periods are Aug 01-31 2021 and Feb 15 to March 14 2022, correct?

**Comment by ericlingerfelt** [comment]
Corrected. We will want to add a tolerance. More like 2021-07-31T00:00:00Z to 2021-08-31T21:00:00Z and likewise for Feb/Mar.
