### ISSUE TITLE
[Ingest] Update archive files changing sensorScanPosition from float to int (matching what is needed in IODA/UFO)

### ISSUE THREAD

**Issue by gthompsnJCSDA** [JCSDA-internal/r2d2-ingest#41]
## Ingest description

It was noted that `sensorScanPosition` is documented as an integer, but IODA and UFO were using mostly floats, with a few usages as integer in UFO.  This has been fixed in code and data files in 4 repos: `ufo`, `ufo-data`, `ioda-converters`, and `ioda-data`.  To prevent Skylab experiments from breaking when those PRs get merged, we need to change all instances of `sensorScanPosition` in our archive files.

Description: 

Data type (_For example, observation, forecast_):  Observation

Other metadata (_For example, provider, observation type, model_):   numerous sensors from multiple providers

## Date range

Start date:  01Aug2021;  15Feb2022

End date:  31Aug2021;  15Mar2022

## Source host and directory/bucket

`Orion:/work2/noaa/fv3-cam/gthompsn/r2d2_temporary` files have now been copied into
`Orion:/work2/noaa/da/jedipara/r2d2-experiments-orion/observation` date-named directories.

## Target data store type (select one)

- [x] archive
- [ ] experiments
- [ ] gfs ensemble
- [ ] other 
    - Please describe: 

## Data store checklist

Data copied into R2D2 on:

- [x] Cheyenne
- [x] Discover
- [x] Orion
- [x] S3 (us-east-1)
- [x] S3 (us-east-2)
- [x] S4

## Dependencies

There are 4 related PRs (ioda-data, ioda-converters, ufo, and ufo-data) listed in the top-level [UFO PR 2916](https://github.com/JCSDA-internal/ufo/pull/2916)

**Comment by gthompsnJCSDA** [comment]
@ericlingerfelt  I fixed dir/file permissions. Thanks.

**Comment by ericlingerfelt** [comment]
```
from r2d2 import R2D2Data

# Step one. Harvest all of the indices from all of the files in your temp dir into an array
indices = []  # store them here

# Step two. Get the R2D2Data object representing each index.
for index in indices:
    r2d2_data_object = R2D2Data.get_by_index(item='observation', index=int(index))

    provider = r2d2_data_object.get_property('provider')
    observation_type = r2d2_data_object.get_property('observation_type')
    file_extension = r2d2_data_object.get_property('file_extension')
    window_start = r2d2_data_object.get_property('window_start')
    window_length = r2d2_data_object.get_property('window_length')
    source_file = '/path/to/source/file'

    # Step three in this loop. Store the files in r2d2-experiments-orion
    index = R2D2Data.store(item='observation',
                           provider=provider,
                           observation_type=observation_type,
                           window_start=window_start,
                           window_length=window_length,
                           source_file=source_file)

    print(index)
    
# Step three. Add the printed indices to the r2d2-ingest issue.
```

**Comment by gthompsnJCSDA** [comment]
The updating of r2d2 and files in `r2d2-experiments-orion` is now complete.  The list of 6481 indexes is found in the text file here.
[file_list.txt](https://github.com/JCSDA-internal/r2d2-ingest/files/12114175/file_list.txt)

**Comment by ericlingerfelt** [comment]
Thanks, @gthompsnJCSDA! I'll take it from here.

**Comment by ericlingerfelt** [comment]
Underway on Orion.

**Comment by gthompsnJCSDA** [comment]
FYI:  I updated the description section of this issue to mention the 4 related PRs as **Dependencies**

It would be terrific if there is a coordinated effort to merge those 4 as near as possible with updating the various hosts because it will impact Skylab experiments.  It may even be best to schedule it at an announced time as best as possible to minimize chance that anyone running a multi-day Skylab experiment will encounter a failure.

**Comment by ericlingerfelt** [comment]
Completed on Orion.

**Comment by ericlingerfelt** [comment]
FYI - I changed phones a week ago and I am still waiting on MSU Orion support staff to help me get DUO set up. I have sent several support emails with only lackluster response. 

After this ingest, we will start requiring all new data files for r2d2-archive to be ingested into us-east-2 and not Orion.

**Comment by ericlingerfelt** [comment]
Done.

**Comment by gthompsnJCSDA** [comment]
> Done.


Thank you Eric.  Do you have an estimate for the transfer of files to other hosts?  I ask because it is probably necessary for Obs team to begin the code/data merges in `ufo` and `ioda` so that experiments do not start breaking.

**Comment by ericlingerfelt** [comment]
![Screenshot 2023-08-07 at 2 24 12 PM](https://github.com/JCSDA-internal/r2d2-ingest/assets/30530322/49aff769-5491-4eb0-84e2-e6f29b64e5a4)

**Comment by gthompsnJCSDA** [comment]
> ![Screenshot 2023-08-07 at 2 24 12 PM](https://user-images.githubusercontent.com/30530322/258918247-49aff769-5491-4eb0-84e2-e6f29b64e5a4.png)

Ooops. I had not checked at top of issue to see the check boxes.  Thanks much!

**Comment by shlyaeva** [comment]
I believe that observation data in https://github.com/JCSDA-internal/r2d2-data also needed updating. We see skylab nightly CI that uses r2d2-data for small experiments failing with:

> Exception: 	source_column:	0
	source_filename:	/home/ubuntu/skylab/jedi_run/jedi-bundle/ioda/src/engines/ioda/include/ioda/Variables/Variable.h
	source_function:	Variable_Implementation ioda::detail::Variable_Base<Variable_Implementation>::read(gsl::span<DataType>, const ioda::Selection &, const ioda::Selection &) const [with DataType = int; Marshaller = ioda::detail::Object_Accessor_Regular<int, int>; TypeWrapper = ioda::Types::GetType_Wrapper<int, 0>; Variable_Implementation = ioda::Variable]
	source_line:	539

that indicates issues with the data in r2d2-data.
 
I am not sure what the procedure is for updating r2d2-data repository with the updated observation files though. @ericlingerfelt could you advise @gthompsnJCSDA how to proceed?

**Comment by ericlingerfelt** [comment]
@shlyaeva, We sure do need an issue on `r2d2-data` for these observations. Thanks for catching this problem! @gthompsnJCSDA and others in OBS, Please create an issue in `r2d2-data` for the observations in _r2d2-archive-<platform>_ that need to be replaced in `r2d2-data@develop`. Thanks!

**Comment by gthompsnJCSDA** [comment]
I will get this started ASAP.

**Comment by ericlingerfelt** [comment]
Thanks, @gthompsnJCSDA! You do not have to call `store` for these. Just get the ones you need converted, convert them, and sit them in a directory somewhere I can access them and leave them labelled `index.nc4`.

**Comment by fabiolrdiniz** [comment]
@ericlingerfelt, please, can you confirm if this has been performed over the archive on Orion? I'm asking because I'm seeing files with floats for the first cycle of SkyLab. Checking the files stored under `/work2/noaa/da/jedipara/r2d2-archive-orion/observation/20220215T210000Z`, the latest files are dated back to Jun 14 13:39.

**Comment by climbfuji** [comment]
@fabiolrdiniz Eric is on vacation until August 17.

**Comment by fabiolrdiniz** [comment]
Oh, thanks for the information, @climbfuji! I wasn't aware of that.

**Comment by ericlingerfelt** [comment]
@fabiolrdiniz, Yes. All of the files provided by @gthompsnJCSDA were ingested and populated globally on all platforms in `r2d2-archive` data stores.

**Comment by ericlingerfelt** [comment]
I know what's wrong. I am repairing now. I will respond here when this is corrected.

**Comment by ericlingerfelt** [comment]
This repair is underway on Orion. I will need to re-sync the others.

**Comment by ericlingerfelt** [comment]
The repair will take a few hours to process. Thanks for your patience.

**Comment by ericlingerfelt** [comment]
The repair is complete on Orion. Should I go ahead and start syncing the other platforms?

**Comment by ericlingerfelt** [comment]
Orion, us-east-1, us-east-2, and Cheyenne are complete. Waiting on S4 (slow) and Discover (reseting password).

**Comment by ericlingerfelt** [comment]
Yes. Thanks! I'm waiting for a response to my NCCS ticket.

**Comment by climbfuji** [comment]
Just the usual sync of r2d2-experiments-orion to Discover, right?

**Comment by ericlingerfelt** [comment]
No. Please sync of r2d2-archive-orion to r2d2-archive-discover. There should be a script in jedipara/bin.

**Comment by climbfuji** [comment]
> No. Please sync of r2d2-archive-orion to r2d2-archive-discover. There should be a script in jedipara/bin.

Of course, that's what I meant. Sorry!

**Comment by climbfuji** [comment]
Sigh, my securID is out of sync again.

**Comment by climbfuji** [comment]
Ok, it's syncing now.

**Comment by climbfuji** [comment]
discover is done

**Comment by ericlingerfelt** [comment]
Done.
