### ISSUE TITLE
[Ingest] Ingest regional backgrounds for composition

### ISSUE THREAD

**Issue by jeromebarre** [JCSDA-internal/r2d2-ingest#42]
## Ingest description

Description: Ingest regional backgrounds (WRF-Chem) over US North-East for composition
Data type: forecast
Other metadata: model = wrf_chem, experiment = oper
Timeline: For Skylab 7
Indices: 1683100 to 1683154

## Date range

Start date: 2023-08-02 00:00:00
End date: 2023-08-02 00:00:00

## Source host and data store

Source host: s4

## Target data store type (select one)

- [x] archive
- [ ] experiments
- [ ] gfsensemble
- [ ] geosensemble
- [ ] other 
    - Please describe: 

## Data ingest processing checklist for the R2D2 Administrator

Data has been ingested into the target data store type on the following data hubs:

- [x] Casper/Derecho (NCAR-Wyoming Supercomputing Center)
- [x] Discover (NASA Center for Climate Simulation)
- [x] Orion/Hercules (Mississippi State University High Performance Computing)
- [x] S3 (jcsda-noaa-aws-us-east-1)
- [x] S3 (jcsda-usaf-aws-us-east-2)
- [x] S4 (Space Science and Engineering Center)

**Comment by ericlingerfelt** [comment]
Please convert this to use the ingest issue template and add the `INGEST` label as well as start the issue title with `[Ingest]`. Thanks!

**Comment by weiwilliam** [comment]
@ericlingerfelt Hi Eric, I have stored the WRF-Chem outputs S4 database.
There are hourly forecasts up to 54 hours initialized from Aug 2 00Z 2023.
The total volume is 46G.
I think the files have been copied to /data/prod/jedi/r2d2-experiments-s4/forecast/20230802T000000Z
Can you take a look and let me know if anything needs to be changed? 
Thank you.

**Comment by ericlingerfelt** [comment]
Is this issue part of release 6?

**Comment by jeromebarre** [comment]
No

**Comment by ericlingerfelt** [comment]
Is this issue still needed?

**Comment by weiwilliam** [comment]
@ericlingerfelt I have the wrfchem output in local database on s4 , /data/prod/jedi/r2d2-experiments-ssec/forecast/20230802T000000Z
We still intend to calculate hofx from the regional outputs for evaluation at some point.
When I stored the wrfchem forecast into s4 local, I specified the following information in yaml file.
```
model: wrf_chem
experiment: oper
domain: 1
resolution: 4km
item: forecast
file_type: wrfout
file_ext: nc
```
Do you need other information?

**Comment by ericlingerfelt** [comment]
HI @weiwilliam, Thank you! I think that should be enough for now.

**Comment by ericlingerfelt** [comment]
Hi @jeromebarre and @weiwilliam, Please do not use `experiment='oper'` as a key/value pair when you ingest data into R2D2. That value is reserved for R2D2 administrators. We will be enforcing this constraint to R2D2's database in the future. 

Why is `domain=1`?

**Comment by ericlingerfelt** [comment]
Also, what is the long name value for 'wrf_chem'? That is, what does this acronym stand for? Thanks!

**Comment by ericlingerfelt** [comment]
Also, please use the data ingest template. I will update this issue to match the template for now.

**Comment by climbfuji** [comment]
> Also, please use the data ingest template. I will update this issue to match the template for now.

Thanks! Folks may be on leave this week, so please proceed with your best guess.

**Comment by weiwilliam** [comment]
@ericlingerfelt Thank you! I will use the template next time.
WRF-Chem stands for the Weather Research and Forecasting (WRF) model coupled with Chemistry
The domain is the index of the forecasts, and it can be 2 or more for nested domains in WRF.
Do you have a doc that specifies the available options for each key value?

**Comment by ericlingerfelt** [comment]
Hi @weiwilliam, Thank you for your help! We are working on improving R2D2's documentation at the moment. I will start this ingest once https://github.com/JCSDA-internal/r2d2-ingest/issues/79 is completed.

**Comment by ericlingerfelt** [comment]
Underway on S4.

**Comment by ericlingerfelt** [comment]
Done.
