### ISSUE TITLE
[Ingest] ingest airnow/open AQ observations

### ISSUE THREAD

**Issue by jeromebarre** [JCSDA-internal/r2d2-ingest#43]
## Description

ingest airnow/open AQ observations for golden month and other period of interest

## Requirements

noew code might need to be added in repo

## Dependencies

complete ioda converter issue: https://github.com/JCSDA-internal/ioda-converters/issues/1297

**Comment by ericlingerfelt** [comment]
Please convert this to use the ingest issue template and add the `INGEST` label as well as start the issue title with `[Ingest]`. Thanks!

**Comment by ericlingerfelt** [comment]
Is this issue part of release 6?

**Comment by jeromebarre** [comment]
No

**Comment by climbfuji** [comment]
@jeromebarre Is this needed for v7?

**Comment by jeromebarre** [comment]
Not really. I am closing this for now as I need to clarify if Sarah and Shih Wei really need to use r2d2 for this.
