### ISSUE TITLE
[Ingest] Static data for GSI B covariances

### ISSUE THREAD

**Issue by shlyaeva** [JCSDA-internal/r2d2-ingest#45]
## Ingest description

Description: 

Data type: static data for GSI background error covariances used in GFS/UFS. (Note: these are new data, a different background error covariance option from BUMP that is already stored in the static data in `skylab-?.0.0/staticb/*`, and we will want to have both of them in the static data).

Other metadata: N/A

## Date range

Start date: N/A

End date: N/A

## Source host and directory/bucket

Source host: orion
Data on orion:
`/work/noaa/da/ashlyaev/jedi/gsi-data/C*` (5 directories for C48, C96, C192, C384, C768).

Data needs to be in the following path in static data (note: these are new static data, there is no analog in the previous skylab versions):
`$(static_data)/skylab-6.0.0/staticb_gsi/C*`

## Target data store type (select one)

static data

## Data store checklist

Data copied into R2D2 on:

- [x] Cheyenne
- [x] Discover
- [x] Orion
- [x] S3 (us-east-1)
- [x] S3 (us-east-2)
- [x] S4

## Associated pull request in [r2d2/scripts](https://github.com/JCSDA-internal/r2d2/tree/develop/scripts) (if creating new ingestion scripts)

*(This instruction will change once we create the r2d2-ingest repository.)*

**Comment by ericlingerfelt** [comment]
I completely missed this issue since it was not assigned to me. Is this ready for ingest and global sync across platforms?

**Comment by shlyaeva** [comment]
Yes it is; I'll assign people next time.

**Comment by ericlingerfelt** [comment]
Done.

**Comment by shlyaeva** [comment]
Thank you @ericlingerfelt!
