### ISSUE TITLE
[Ingest] Get, (convert?) and ingest c48, UFS compatible ensemble data

### ISSUE THREAD

**Issue by cmgas** [JCSDA-internal/r2d2-ingest#46]

**Comment by cmgas** [comment]
On hold until I hear back

**Comment by ericlingerfelt** [comment]
Hi @cmgas, Any updates on this issue? Just checking. Thanks!

**Comment by ericlingerfelt** [comment]
Hi @cmgas, Any updates on this issue? Just checking. Thanks!

**Comment by climbfuji** [comment]
@cmgas Is this still needed, or shall we close as "not planned"?
