### ISSUE TITLE
[Ingest]  Need to replace the `small` experiment GOES-ABI files because of an internal data type problem

### ISSUE THREAD

**Issue by gthompsnJCSDA** [JCSDA-internal/r2d2-ingest#49]
## Ingest description

The files associated with GOES-ABI for the `small` Skylab experiment have floating point values instead of integers for the `PreQC/brightnessTemperature` variable.  This crashes IODA reader in the Skylab experiments.  The regular full-size files are correct, so a new set of files will be made for the small versions.

Description: 

Data type (_For example, observation, forecast_):  Observation

Other metadata (_For example, provider, observation type, model_):  GOES-ABI (16 and 17), brightness temperature, 64km sampling (`abi_g16_bt_64km` and `abi_g17_bt_64km` are the two observation_types). While the original `provider` is NOAA, these files are being set into the `coarseSampling` provider.

## Date range

Start date: 2022-02-14T21:00:00Z
End date: 2022-02-17T15:00:00Z

The full date list is:
2022-02-14 21:00:00
2022-02-15 03:00:00
2022-02-15 09:00:00
2022-02-15 15:00:00
2022-02-15 21:00:00
2022-02-16 03:00:00
2022-02-16 09:00:00
2022-02-16 15:00:00
2022-02-16 21:00:00
2022-02-17 03:00:00
2022-02-17 09:00:00
2022-02-17 15:00:00

## Source host and directory/bucket

Source host:  Orion:/work2/noaa/fv3-cam/gthompsn/r2d2_temporary
File list:
12373.nc4
12374.nc4
12387.nc4
12395.nc4
12437.nc4
12467.nc4
12468.nc4
12497.nc4
12498.nc4
12527.nc4
12528.nc4
12557.nc4
12587.nc4
12588.nc4
12617.nc4
12618.nc4
12647.nc4
12648.nc4
12677.nc4
12707.nc4
12708.nc4

## Target data store type (select one)

- [x] archive
- [ ] experiments
- [ ] gfs ensemble
- [ ] other 
    - Please describe: 

## Data store checklist

Data copied into R2D2 on:

- [x] Cheyenne
- [x] Discover
- [x] Orion
- [x] S3 (us-east-1)
- [x] S3 (us-east-2)
- [ ] S4

**Comment by gthompsnJCSDA** [comment]
@ericlingerfelt  I believe this ingest item is now ready to go in large part with help from @fabiolrdiniz

**Comment by fabiolrdiniz** [comment]
@gthompsnJCSDA, just to confirm, ABI data is only being changed for these dates, right?
```
2022-02-14 21:00:00
2022-02-15 03:00:00
2022-02-15 09:00:00
2022-02-15 15:00:00
2022-02-15 21:00:00
2022-02-16 03:00:00
2022-02-16 09:00:00
2022-02-16 15:00:00
2022-02-16 21:00:00
2022-02-17 03:00:00
2022-02-17 09:00:00
2022-02-17 15:00:00
```

**Comment by gthompsnJCSDA** [comment]
@fabiolrdiniz  Correct. There are other dates in the `coarseSampling` total data set from the 2021Aug "golden month" but for the ABI data, those dates did not exist.  So I corrected the Issue Description section appropriately.

**Comment by ericlingerfelt** [comment]
These files have been re-stored in `r2d2-archive-orion`. Do they need to be tested on Orion before I sync to the other platforms? Thanks, @gthompsnJCSDA and @fabiolrdiniz!

**Comment by gthompsnJCSDA** [comment]
@ericlingerfelt   Yes, I tested in a skylab experiment and the files now work in the `atm-land-small` experiment.  Thanks!!  You can safely sync to other platforms when you have time.

**Comment by fabiolrdiniz** [comment]
Do we have a PR in r2d2-data updating those files as well?

**Comment by ericlingerfelt** [comment]
I don't think so.

**Comment by ericlingerfelt** [comment]
Syncing across platforms.

**Comment by ericlingerfelt** [comment]
Is OBS going to create the r2d2-data issue?

**Comment by ericlingerfelt** [comment]
Waiting on S4 (slow).

**Comment by ericlingerfelt** [comment]
Done.
