### ISSUE TITLE
[Ingest] Need MPAS files propagated to jedipara $EWOK_STATIC_DATA accounts

### ISSUE THREAD

**Issue by svahl991** [JCSDA-internal/r2d2-ingest#50]
## Ingest description

Description: In order to support running MPAS experiments with Skylab, there are certain required static files that are currently scattered about `glade` directories on Cheyenne that are controlled by people on the MMM JEDI team. These files need to be copied into the `jedipara` accounts, both to bring them under our control and to eventually support running on other platforms besides Cheyenne.

I think the easiest way to describe the required files is through pseudo-`bash` commands that could be executed on Cheyenne by someone with proper permissions:

Data type: static

## Source host and directory/bucket

Source host: cheyenne

Data store directory path or S3 bucket path (_with wildcards if needed_):

```
cp /glade/p/mmm/parc/liuz/pandac_common/static_from_duda/x1.40962.* $EWOK_STATIC_DATA/skylab-6.0.0/mpas/120km
cp /glade/scratch/bjung/pandac/bjung_3dvar-60-iter_O120km_VarBC/ExternalAnalyses/120km/2018041418/x1.40962.init.2018-04-14_18.00.00.nc $EWOK_STATIC_DATA/skylab-6.0.0/mpas/120km/static.40962.nc
cp /glade/scratch/bjung/ewok_prep/bg_480km/x1.2562.init.2022-02-14_18.00.00.nc $EWOK_STATIC_DATA/skylab-6.0.0/mpas/480km/static.2562.nc
export MPAS_BSTATIC_DIR=/glade/p/mmm/parc/liuz/pandac_common/BUMP_files/20230522_yr5
cp ${MPAS_BSTATIC_DIR}/120km.CMAT_00/mpas.stddev_0p33.2018-04-15_00.00.00.nc $EWOK_STATIC_DATA/skylab-6.0.0/staticb/120km
cp ${MPAS_BSTATIC_DIR}/120km.VBAL_00/mpas_vbal* $EWOK_STATIC_DATA/skylab-6.0.0/staticb/120km/VerticalBalance
cp ${MPAS_BSTATIC_DIR}/120km.NICAS_00/mpas_parametersbump_cov* $EWOK_STATIC_DATA/skylab-6.0.0/staticb/120km/NICAS**
```

## Target data store type (select one)

- [ ] archive
- [ ] experiments
- [ ] gfs ensemble
- [x] other 
    - Please describe: static

## Data store checklist

Data copied into static directory on:

- [x] Cheyenne
- [x] Discover
- [x] Orion
- [x] S3 (us-east-1)
- [x] S3 (us-east-2)
- [x] S4

## Acceptance Criteria (Definition of Done)

The 3DVar MPAS Skylab experiment can successfully run and cycle without accessing any static files on Cheyenne outside of those under `$EWOK_STATIC_DATA`

## Dependencies

Does this block progress on other issues?
 - blocking https://github.com/JCSDA-internal/skylab/issues/95

**Comment by ericlingerfelt** [comment]
Applying ingest issue template to this ingest issue.

**Comment by ericlingerfelt** [comment]
These files have been copied into /glade/p/mmm/jedipara/static/ on cheyenne. Are these going to be tested in place before I copy them globally to all platforms? Thanks, @svahl991!

**Comment by svahl991** [comment]
Yes, thanks! I'll modify my skylab code to use the new location and give it a test and let you know.

**Comment by svahl991** [comment]
I've tested and seems to work fine. I think you can copy globally!

**Comment by ericlingerfelt** [comment]
Waiting on S4 (slow).

**Comment by shlyaeva** [comment]
I have just noticed that these data are not available in the static directory on the new pcluster; reopening. Let me know if I can assist with copying the data (I haven't done it before but can learn :)).

```
$ ls /mnt/experiments-efs/skylab-v5/static/skylab-6.0.0/mpas/
ls: cannot access '/mnt/experiments-efs/skylab-v5/static/skylab-6.0.0/mpas/': No such file or directory
```

**Comment by climbfuji** [comment]
I can copy the data.

**Comment by climbfuji** [comment]
On the way ...

**Comment by shlyaeva** [comment]
> But note that the path needs to be /mnt/experiments-efs/skylab-v6/static/skylab-6.0.0/mpas/ because skylab-v5/.../skylab-6.0.0 does not make sense.

Agreed; happy to use skylab-v6 instead.

**Comment by climbfuji** [comment]
Data is available in `/mnt/experiments-efs/skylab-v6/static/skylab-6.0.0/`, please check and close if satisfied.

**Comment by shlyaeva** [comment]
Great, thank you, the data are fetched now successfully on pcluster; closing.
