### ISSUE TITLE
[Ingest] GEOS ensemble backgrounds

### ISSUE THREAD

**Issue by jeromebarre** [JCSDA-internal/r2d2-ingest#51]
## Ingest description

Description: 

Data type: forecast

Other metadata: geos

## Date range

Start date: 20210803T15Z

End date: 20210818T15Z

## Source host and directory/bucket

Source host:  discover

Data store directory path or S3 bucket path (_with wildcards if needed_):
`/gpfsm/dnb05/projects/p139/rtodling/archive/Others/Jerome/x48rt/atmens/Y2021/M08`

stored in tar files, needs extraction.
Two files should be extracted:
`x48rt.atmens_ebaer.YYYYMMDD_HHz.tar`
`x48rt.atmens_ebkgx.YYYYMMDD_HHz.tar` (there are also `*ebkg.*` files without the 'x' but we're not interested in those)

There are 32 members stored in separated directories `mem${member}`

From `ebaer` extraction ingest `x48rt.abkg.eta.YYYYMMDD_HHMMz.nc4`. 3 hourly files.

From `ebkgx` extraction ingest  ` x48rt.bkg_clcv.YYYYMMDD_HHMMz.nc4` 1 hour files. Ideally, store all but if space is a concern here I think it would be fine to have matching hours with `ebaer` files. 

## Target data store type (select one)

- [ ] archive
- [ ] experiments
- [ ] gfs ensemble
- [X] other: 
    - Please describe: geosensemble 

## Data store checklist

Data copied into R2D2 on:

- [x] Discover
- [x] Orion
- [x] S3 (us-east-1)
- [x] S3 (us-east-2)
- [x] S4

**Comment by jeromebarre** [comment]
@rtodling just FYI, I finally made a request. Once this is finished you could free up your space on discover. Thanks for your patience.

**Comment by ericlingerfelt** [comment]
There are many more questions to be answered concerning this issue. They involve a new `geosensemble` data store as listed in this issue and a variety of updates to the GEOS model schema in R2D2's database. Also, INFRA does not ingest data files. We only provide support for read-only data stores. In this case, COMPO will need to ingest these into `r2d2-experiments-discover` and then we will move those files to `r2d2-archive-discover` and the other supported platforms. Thanks, @jeromebarre!

**Comment by ericlingerfelt** [comment]
We should probably meet to discuss after I review the details of these forecast files.

**Comment by ericlingerfelt** [comment]
From meeting on 09/06/23: 

- There are two file types for the new `geos` `model` schema: `abkg.eta` and `bkg_clcv`. 
- The three `abkg.eta` member files per date are stored by directory date and then PT0H, PT3H, and PT6H. 
- There may be overlapping files in adjacent dated directories. 
- The six `bkg_clcv` files are stored by directory date and then PT0H - PT6H. We have the option of trimming these down to the 3 hour intervals. 

Next steps: 

- Add these file types to the `model` schema for `geos`. 
- Calculate the total filesize footprint of this entire data set. 
- Work with @climbfuji on possible data store needs and solutions.

**Comment by jeromebarre** [comment]
We might the add an offset meaning we should have PT3H-PT9H. I will come up with an example of an ingest script to clarify.

**Comment by jeromebarre** [comment]
I just got this email from Ricardo:
```
Hi Jerome,
Hope all is well.
I want to check w/ you about the files you asked me to keep for you. I have some serious space issue and need to clean up as much as I can. Have you copied over the files you needed from me? Can I clean up now?
Pls let me know.
```
@ericlingerfelt if I come up with an ingest script after untaring a few cycles could we ingest this this week?

**Comment by ericlingerfelt** [comment]
@jeromebarre, What is the approximate total size on disk of the ingest? Is there any way we can make a copy so that Ricardo can delete his copy? 

You will have to ingest these backgrounds into `r2d2-experiments-discover` anyway before I move them into the new, yet-to-be-created `r2d2-geosensemble-discover` data store. Please record the output so that I can access these files by index.

**Comment by jeromebarre** [comment]
```
**jbarre@discover11:/gpfsm/dnb05/projects/p139/rtodling/archive/Others/Jerome/x48rt/atmens/Y2021/M08> du -sh
5.9T	
```

**Comment by ericlingerfelt** [comment]
@jeromebarre, I talked with @climbfuji. Please go ahead and ingest these into r2d2-experiments-discover and record the output please. Thanks!

**Comment by jeromebarre** [comment]
I'll try to do this tonight. Thanks!

**Comment by jeromebarre** [comment]
@ericlingerfelt This has been ingested on Discover, please check the ingest output files on:
`/discover/nobackup/jbarre/jedidev/jedi-bundle/r2d2-ingest/scripts/geos_cf/fc/meteo_geos_ingest`
`/discover/nobackup/jbarre/jedidev/jedi-bundle/r2d2-ingest/scripts/geos_cf/fc/aero_geos_ingest`

Since this is just a test period ensemble I ingested only 5.5 days.

The ingest scripts are here: https://github.com/JCSDA-internal/r2d2-ingest/pull/70

**Comment by jeromebarre** [comment]
@ericlingerfelt any updates on the ingest synching? Thanks!

**Comment by jeromebarre** [comment]
@climbfuji @ericlingerfelt what is the status on this? Thanks!

**Comment by ericlingerfelt** [comment]
Hi @jeromebarre, We'll do our best to get this completed during the next sprint. Thanks!

**Comment by jeromebarre** [comment]
Please hold on syncing this as there are offset times in the data. We are working on correcting this and will let you know when this is ready. Thanks

**Comment by jeromebarre** [comment]
Will have the data corrected by the end of today. Thanks

**Comment by ericlingerfelt** [comment]
Hi @jeromebarre, The check boxes under `Data store checklist` are for **_after_** each platform has been populated. I use those to keep track of what has been done.

**Comment by jeromebarre** [comment]
Ha ok sorry

**Comment by ericlingerfelt** [comment]
Thanks!

**Comment by jeromebarre** [comment]
The ingest has been updated and the info is still in the same files:
```
/discover/nobackup/jbarre/jedidev/jedi-bundle/r2d2-ingest/scripts/geos_cf/fc/meteo_geos_ingest
/discover/nobackup/jbarre/jedidev/jedi-bundle/r2d2-ingest/scripts/geos_cf/fc/aero_geos_ingest
```

**Comment by ericlingerfelt** [comment]
These files were ingested using `experiment='oper'`. This ingestion will require a little extra time since a search must be performed to identify all of the required data files.

**Comment by jeromebarre** [comment]
> These files were ingested using `experiment='oper'`. This ingestion will require a little extra time since a search must be performed to identify all of the required data files.

I can remove them and re-ingest them with a different experiment name if that's easier for you. Please let me know.

**Comment by ericlingerfelt** [comment]
It's ok. I'll take it from here, @jeromebarre. We'll get this wrapped up next week.

**Comment by jeromebarre** [comment]
all the files ingested are listed in here:
```
/discover/nobackup/jbarre/jedidev/jedi-bundle/r2d2-ingest/scripts/geos_cf/fc/meteo_geos_ingest
/discover/nobackup/jbarre/jedidev/jedi-bundle/r2d2-ingest/scripts/geos_cf/fc/aero_geos_ingest
```

**Comment by ericlingerfelt** [comment]
The data store `r2d2-geosensemble-discover` has been created.

**Comment by ericlingerfelt** [comment]
Completed on Discover. Creating data stores on AWS us-east-1 and us-east-2 and starting sync.

**Comment by ericlingerfelt** [comment]
Done on us-east-1 and us-east-2.

**Comment by ericlingerfelt** [comment]
Working on Orion and S4.

**Comment by ericlingerfelt** [comment]
Done.

**Comment by jeromebarre** [comment]
@xian22 @mer-a-o @tom-8822 @ytremolet @shlyaeva @cmgas FYI
