### ISSUE TITLE
[Ingest] Need 480km MPAS forecast added for 2022-02-14

### ISSUE THREAD

**Issue by svahl991** [JCSDA-internal/r2d2-ingest#52]
## Ingest description

*(Instructions: Please provide values for the following entries.)*

Description: 

Data type (_For example, observation, forecast_): Forecast

Other metadata (_For example, provider, observation type, model_): 
Step: PT6H
model: mpas
date: 20220214T180000Z
experiment: oper
resolution: 480km

## Date range

See above for date
## Source host and directory/bucket

Source host: cheyenne

Data store directory path or S3 bucket path (_with wildcards if needed_):
`/glade/scratch/bjung/ewok_prep/bg_480km/mpasout.2022-02-15_00.00.00.nc`

## Target data store type (select one)

- [x] archive
- [ ] experiments
- [ ] gfs ensemble
- [ ] other 
    - Please describe: 

## Data store checklist

Data copied into R2D2 on:

- [x] Cheyenne
- [x] Discover
- [x] Orion
- [x] S3 (us-east-1)
- [x] S3 (us-east-2)
- [ ] S4

**Comment by ericlingerfelt** [comment]
Working on this now.

**Comment by ericlingerfelt** [comment]
Done on cheyenne.

**Comment by ericlingerfelt** [comment]
Syncing other platforms.

**Comment by ericlingerfelt** [comment]
Waiting on S4 (slow).

**Comment by ericlingerfelt** [comment]
Done.
