### ISSUE TITLE
[Ingest] addition of AMSR/2 and GMI for Skylab v6

### ISSUE THREAD

**Issue by BenjaminRuston** [JCSDA-internal/r2d2-ingest#53]
## Ingest description

the AMSR/2 and GMI sensors have been processed and should be distributed for inclusion in the Skylab v6 release

Description: 

Data type:
observation

Other metadata: 
GMI_GPM 
AMSR2_GCOS-W1

## Date range

Start date:  01Aug2021; 15Feb2022

End date: 01Sep2021; 15Mar2022

## Source host and directory/bucket

Source host: 
Orion

Data store directory path or S3 bucket path (_with wildcards if needed_):

## Target data store type (select one)

- [x] archive
- [ ] experiments
- [ ] gfs ensemble
- [ ] other 
    - Please describe: 

## Data store checklist

Data copied into R2D2 on:

- [x] Cheyenne
- [x] Discover
- [x] Orion
- [x] S3 (us-east-1)
- [x] S3 (us-east-2)
- [ ] S4

**Comment by BenjaminRuston** [comment]
added an INFRA epic not sure if this is the correct one, also should add the coarseSampling to this as well

**Comment by ericlingerfelt** [comment]
Do you have the `observation_type`s used or indices created when you stored these into `r2d2-experiments-orion`? Thanks, @BenjaminRuston!

**Comment by BenjaminRuston** [comment]
@ericlingerfelt here's the full log files


[r2d2_populate_amsr2_2021.txt](https://github.com/JCSDA-internal/r2d2-ingest/files/12469364/r2d2_populate_amsr2_2021.txt)
[r2d2_populate_amsr2_2022.txt](https://github.com/JCSDA-internal/r2d2-ingest/files/12469368/r2d2_populate_amsr2_2022.txt)
[r2d2_populate_gmi_2021.txt](https://github.com/JCSDA-internal/r2d2-ingest/files/12469369/r2d2_populate_gmi_2021.txt)
[r2d2_populate_gmi_2022.txt](https://github.com/JCSDA-internal/r2d2-ingest/files/12469371/r2d2_populate_gmi_2022.txt)

**Comment by ericlingerfelt** [comment]
Thanks, @BenjaminRuston!

**Comment by ericlingerfelt** [comment]
Done on Orion.

**Comment by ericlingerfelt** [comment]
Waiting on S4 (slow).

**Comment by ericlingerfelt** [comment]
Done.
