### ISSUE TITLE
[Ingest] snowDepth from the GHCN network

### ISSUE THREAD

**Issue by BenjaminRuston** [JCSDA-internal/r2d2-ingest#54]
## Ingest description

ingest of the snowDepth data from the GHCN network for use in Skylab runs in the v6 release

Description: 

Data type `observation`

observation type. `snowdepth_ghcn`

## Date range

Start date: 20210731T21Z; 20220214T21Z

End date: 20210831T21Z; 20220314T21Z

## Source host and directory/bucket

Source host: Orion

Data store directory path or S3 bucket path (_with wildcards if needed_):

## Target data store type (select one)

- [x] archive
- [ ] experiments
- [ ] gfs ensemble
- [ ] other 
    - Please describe: 

## Data store checklist

Data copied into R2D2 on:

- [x] Cheyenne
- [x] Discover
- [x] Orion
- [x] S3 (us-east-1)
- [x] S3 (us-east-2)
- [ ] S4

**Comment by BenjaminRuston** [comment]
logfile for Aug2021 ingest:
[snowdepth_ghcn_2021.txt](https://github.com/JCSDA-internal/r2d2-ingest/files/12501338/snowdepth_ghcn_2021.txt)

log file for 15Feb-15Mar2022 Ingest:
[snowdepth_ghcn_2022.txt](https://github.com/JCSDA-internal/r2d2-ingest/files/12501339/snowdepth_ghcn_2022.txt)

**Comment by BenjaminRuston** [comment]
@ericlingerfelt know a lot of irons in the fire, are you able to get to this as we'd like this data in skylab v6 and in the round of testing starting next week

**Comment by BenjaminRuston** [comment]
@climbfuji this for us is the highest priority for the bi-weekly testing and data freeze above the skylab small ingest requests

**Comment by climbfuji** [comment]
> @climbfuji this for us is the highest priority for the bi-weekly testing and data freeze above the skylab small ingest requests

@ericlingerfelt FYI

**Comment by ericlingerfelt** [comment]
I'll start this work today.

**Comment by ericlingerfelt** [comment]
In progress.

**Comment by ericlingerfelt** [comment]
Done on Orion. Working on sync now.

**Comment by ericlingerfelt** [comment]
Waiting on S4 (slow).

**Comment by ericlingerfelt** [comment]
Done.
