### ISSUE TITLE
[Ingest] gdas ensemble data for period 20220215T18 to 20220222T18, 25 members

### ISSUE THREAD

**Issue by climbfuji** [JCSDA-internal/r2d2-ingest#56]
## Ingest description

We need to ingest gdas ensemble data (background and ensemble members) for period 20220215T18 to 20220222T18, 25 members. The raw data are 3-hourly datasets 003, 006, 009, a cycle every 6 hours. Steps:
- [x] fetch `atmf` files from HPSS on Hera
- [x] fetch `sfcf` files from HPSS on Hera
- [x] transfer `atmf` files to S3 bucket in AWS USAF us-east-2 `s3://ingest-hpss/gdas/`
- [x] transfer `sfcf` files to S3 bucket in AWS USAF us-east-2
- [x] build UFS_UTILS on new R&D hpc6a cluster (@climbfuji)
- [x] transfer fix files from Orion to S3 bucket in AWS USAF us-east-2
- [x] Fix files available on pcluster --> files in `/mnt/experiments-efs/clementine.gas/ingest_ufs/ufs-fix`
- [x] download gdas data to AWS parallel cluster or implement direct access in conversion workflow (@shlyaeva ) --> files in `/mnt/experiments-efs/anna.shlyaeva/ensemble.2022021518` and `/mnt/experiments-efs/anna.shlyaeva/control.2022021518` 
- [x] convert to desired resolution and format using UFS_UTILS on AWS parallel cluster (@cmgas) --> files in `/mnt/experiments-efs/clementine.gas/ingest_ufs`
- [x] convert from coldstart to warmstart with the ufs-weather-model (@cmgas) 
- [x] store in local r2d2 data store (@cmgas) right now, in expid `86d563`
- [x] ingest in authoritative database (@ericlingerfelt) right now, in expid `86d563` issue in #69 
- [ ] Put the hpss download script on Hera in version control (@climbfuji): https://github.com/JCSDA-internal/r2d2-ingest/pull/72
- [x] Delete original data (only the model data, not the fixed data) from `ingest-hpss` bucket (@climbfuji)

Description: 

Data type (_For example, observation, forecast_): forecast

Other metadata (_For example, provider, observation type, model_):  model

## Date range

Start date: 20220215T18

End date: 20220222T18

## Source host and directory/bucket

Source host: AWS parallel cluster

Data store directory path or S3 bucket path (_with wildcards if needed_): to be determined

## Target data store type (select one)

- [ ] archive
- [ ] experiments
- [x] gfs ensemble
- [ ] other 
    - Please describe: 

## Data store checklist

Data copied into R2D2 on:

- [ ] Cheyenne
- [ ] Discover
- [ ] Orion
- [ ] S3 (us-east-1)
- [ ] S3 (us-east-2)
- [ ] S4

## Associated pull request in [r2d2/scripts](https://github.com/JCSDA-internal/r2d2/tree/develop/scripts) (if creating new ingestion scripts)

**to be determined**

**Comment by cmgas** [comment]
@climbfuji , we also need to fix files but I don't know which ones are needed for which resolution. They exist on Orion and are linked automatically on supported platforms with `ufs_utils/fix/link_fixdirs.sh` . 
We are also missing all the surface files for all the members / dates (named `sfcf`, they would be next to the `atmf` files I think)

**Comment by climbfuji** [comment]
@cmgas Can you update this issue please?

**Comment by cmgas** [comment]
I added some of the steps we have been working on and checked more boxes yesterday, was there something else needing modifications?

**Comment by climbfuji** [comment]
If the above checklist in the PR description is up to date, then all good for now, thanks!
