### ISSUE TITLE
[Ingest] Ingest missing observations for the sensorScanPosition conversion

### ISSUE THREAD

**Issue by ericlingerfelt** [JCSDA-internal/r2d2-ingest#58]
## Ingest description

Description: 

This issue addresses the need to convert and ingest missing observations into R2D2. 

Here are the indices to be fetched, converted, and stored, and synced.
`
3944 3945 3946 3947 3948 3950 3951 3953 3954 3956 3957 3959 3960 3961 3963 3964 3965 3966 3967 3969 3974 3975 3976 3977 3978 3979 3980 3981 3984 3986 3987 3988 3991 3992 3995 3998 3999 4001`

Data type: observation

Other metadata: 

## Date range

Dates: 20180414T210000Z and 20201214T210000Z

## Source host and directory/bucket

Source host: TBD

Data store directory path or S3 bucket path: TDB

## Target data store type (select one)

- [x] archive
- [ ] experiments
- [ ] gfs ensemble
- [ ] other 
    - Please describe: 

## Data store checklist

Data copied into R2D2 on:

- [x] Cheyenne
- [x] Discover
- [x] Orion
- [x] S3 (us-east-1)
- [x] S3 (us-east-2)
- [ ] S4

**Comment by fabiolrdiniz** [comment]
Hi, @ericlingerfelt. Please, let us know how can we prepare it for you to populate the archive. We can fetch those indices, convert the variables, and store the files using the same key pair values (but now being stored in the experiments data store). Then we can pass the new indices in the experiments data store to be migrated to the archive.

I didn't check, but if there is a mix of file extensions & providers, then it's going to be messy if we temporarily reingest them using a generic set of key pair values (e.g., `nc` & the `testing` provider).

**Comment by ericlingerfelt** [comment]
Hi @fabiolrdiniz, I think at this point the easiest way would be to copy these paths into a single directory on Orion, convert them, and then tell me where they are. I can take care of the rest. Thanks! We'll get this corrected ASAP.

```
/work2/noaa/da/jedipara/r2d2-archive-orion/observation/20180414T210000Z/3944.nc4
/work2/noaa/da/jedipara/r2d2-archive-orion/observation/20180414T210000Z/3945.nc4
/work2/noaa/da/jedipara/r2d2-archive-orion/observation/20180414T210000Z/3946.nc4
/work2/noaa/da/jedipara/r2d2-archive-orion/observation/20180414T210000Z/3947.nc4
/work2/noaa/da/jedipara/r2d2-archive-orion/observation/20180414T210000Z/3948.nc4
/work2/noaa/da/jedipara/r2d2-archive-orion/observation/20180414T210000Z/3950.nc4
/work2/noaa/da/jedipara/r2d2-archive-orion/observation/20180414T210000Z/3951.nc4
/work2/noaa/da/jedipara/r2d2-archive-orion/observation/20180414T210000Z/3953.nc4
/work2/noaa/da/jedipara/r2d2-archive-orion/observation/20180414T210000Z/3954.nc4
/work2/noaa/da/jedipara/r2d2-archive-orion/observation/20180414T210000Z/3956.nc4
/work2/noaa/da/jedipara/r2d2-archive-orion/observation/20180414T210000Z/3957.nc4
/work2/noaa/da/jedipara/r2d2-archive-orion/observation/20180414T210000Z/3959.nc4
/work2/noaa/da/jedipara/r2d2-archive-orion/observation/20180414T210000Z/3960.nc4
/work2/noaa/da/jedipara/r2d2-archive-orion/observation/20180414T210000Z/3961.nc4
/work2/noaa/da/jedipara/r2d2-archive-orion/observation/20180414T210000Z/3963.nc4
/work2/noaa/da/jedipara/r2d2-archive-orion/observation/20180414T210000Z/3964.nc4
/work2/noaa/da/jedipara/r2d2-archive-orion/observation/20180414T210000Z/3965.nc4
/work2/noaa/da/jedipara/r2d2-archive-orion/observation/20180414T210000Z/3966.nc4
/work2/noaa/da/jedipara/r2d2-archive-orion/observation/20180414T210000Z/3967.nc4
/work2/noaa/da/jedipara/r2d2-archive-orion/observation/20180414T210000Z/3969.nc4
/work2/noaa/da/jedipara/r2d2-archive-orion/observation/20201214T210000Z/3974.nc4
/work2/noaa/da/jedipara/r2d2-archive-orion/observation/20201214T210000Z/3975.nc4
/work2/noaa/da/jedipara/r2d2-archive-orion/observation/20201214T210000Z/3976.nc4
/work2/noaa/da/jedipara/r2d2-archive-orion/observation/20201214T210000Z/3977.nc4
/work2/noaa/da/jedipara/r2d2-archive-orion/observation/20201214T210000Z/3978.nc4
/work2/noaa/da/jedipara/r2d2-archive-orion/observation/20201214T210000Z/3979.nc4
/work2/noaa/da/jedipara/r2d2-archive-orion/observation/20201214T210000Z/3980.nc4
/work2/noaa/da/jedipara/r2d2-archive-orion/observation/20201214T210000Z/3981.nc4
/work2/noaa/da/jedipara/r2d2-archive-orion/observation/20201214T210000Z/3984.nc4
/work2/noaa/da/jedipara/r2d2-archive-orion/observation/20201214T210000Z/3986.nc4
/work2/noaa/da/jedipara/r2d2-archive-orion/observation/20201214T210000Z/3987.nc4
/work2/noaa/da/jedipara/r2d2-archive-orion/observation/20201214T210000Z/3988.nc4
/work2/noaa/da/jedipara/r2d2-archive-orion/observation/20201214T210000Z/3991.nc4
/work2/noaa/da/jedipara/r2d2-archive-orion/observation/20201214T210000Z/3992.nc4
/work2/noaa/da/jedipara/r2d2-archive-orion/observation/20201214T210000Z/3995.nc4
/work2/noaa/da/jedipara/r2d2-archive-orion/observation/20201214T210000Z/3998.nc4
/work2/noaa/da/jedipara/r2d2-archive-orion/observation/20201214T210000Z/3999.nc4
/work2/noaa/da/jedipara/r2d2-archive-orion/observation/20201214T210000Z/4001.nc4
```

**Comment by ericlingerfelt** [comment]
Let's see if we can get this done today. I am out tomorrow and Thursday for dental implant surgery.

**Comment by fabiolrdiniz** [comment]
Sure. I just created them inside Orion on this directory: `/work2/noaa/jcsda/fdiniz/Others/Eric`. Inside that folder, you will find 3 files per index:

- `????`: the file fetched by r2d2 (a soft link pointing to the archive)
- `????.original`: a local copy of the file above
- `????.modified`: the file above with the expected modification

@gthompsnJCSDA, it would be nice if another set of eyes could go over those files.

**Comment by gthompsnJCSDA** [comment]
I made a quick check of 5 randomly picked files in Fabio's directory and they look correct to me.  Thank you Fabio!!!

**Comment by ericlingerfelt** [comment]
Thank you @gthompsnJCSDA and @fabiolrdiniz for your help!

**Comment by ericlingerfelt** [comment]
Underway on Orion.

**Comment by ericlingerfelt** [comment]
Done on Orion. Starting the sync.

**Comment by ericlingerfelt** [comment]
Waiting on S4 (slow).

**Comment by ericlingerfelt** [comment]
Done.

**Comment by fabiolrdiniz** [comment]
Thanks, @ericlingerfelt!
