### ISSUE TITLE
[Ingest] TEMPO NO2 observations

### ISSUE THREAD

**Issue by jeromebarre** [JCSDA-internal/r2d2-ingest#59]
## Ingest description

*(Instructions: Please provide values for the following entries.)*
Ingest script here on Orion:
https://github.com/JCSDA-internal/r2d2-ingest/pull/57
Make sure to use or replicate what this script does as it fills up with the empty obs file when there is no obs. 
If obs file is missing **SKYLAB WILL CRASH**

The yaml contains all the info:

start: 2021-08-01T12:00:00Z
end: 2021-08-11T18:00:00Z
provider: nasa
item: observation
window_length: PT6H
source_path: /work/noaa/da/barre/get_obs/ioda_tempo_no2/
obs_type: tempo_no2_tropo

## Target data store type (select one)

- [x] archive
- [ ] experiments
- [ ] gfs ensemble
- [ ] other 
    - Please describe:

## Data store checklist

Data copied into R2D2 on:

- [x] Cheyenne
- [x] Discover
- [x] Orion
- [x] S3 (us-east-1)
- [x] S3 (us-east-2)
- [ ] S4

**Comment by ericlingerfelt** [comment]
Hi @jeromebarre, Have these observations been ingested into `r2d2-experiments-orion` yet? If not, please ingest them, record the indices that result from your `store` calls, and then I will move them to the `r2d2-archive-<host>` data stores. Thanks!

**Comment by jeromebarre** [comment]
I will make sure they are all ingested and let you know asap.

**Comment by ericlingerfelt** [comment]
Thanks! Each call to `store` returns an integer. It would be great to have those in a file that I can copy and paste if possible.

**Comment by jeromebarre** [comment]
I will redirect the execution output to a file

**Comment by jeromebarre** [comment]
TEMPO data are now ingested see output on Orion at:
`/home/barre/ingest_tempo`

**Comment by ericlingerfelt** [comment]
In progress on Orion.

**Comment by ericlingerfelt** [comment]
I can not access your home directory. Please place these files on `work2` somewhere. Thanks!

**Comment by ericlingerfelt** [comment]
I can access now. Thanks!

**Comment by ericlingerfelt** [comment]
Underway on Orion.

**Comment by ericlingerfelt** [comment]
Completed on Orion. Starting sync.

**Comment by ericlingerfelt** [comment]
Waiting on Cheyenne and S4.

**Comment by ericlingerfelt** [comment]
Waiting on S4.

**Comment by ericlingerfelt** [comment]
Done.
