### ISSUE TITLE
add updated atmospheric data to r2d2 for Skylab v4

### ISSUE THREAD

**Issue by fabiolrdiniz** [JCSDA-internal/r2d2-ingest#6]
@BenjaminRuston commented on [Wed Mar 22 2023](https://github.com/JCSDA-internal/r2d2-data/issues/38)

## Ingest description

Description: 
this updates the atmospheric observations for the 2022 15Feb-15Mar time period, it includes:
AMV satellite winds
ATMS
COWVR
TEMPEST
TROPICS
radiosonde LDM (high resolution)
radiosonde TAC (low resolution text messages)

Data type: atmospheric observations

## Date range

2021-07-31T21:00:00Z - 2021-08-31T21:00:00Z (AMV's only)
2022-02-14T21:00:00Z - 2022-03-14T21:00:00Z

## Source host and directory/bucket

Source host: 

Cheyenne:
`/glade/scratch/benr/r2d2_experiments_cheyenne/noaa/obs`

## Target data store type (select one)

- [x] archive
- [ ] experiments
- [ ] gfs ensemble
- [ ] other 
    - Please describe: r2d2-data repo

## Data store checklist

Data copied into R2D2 on:

- [x] Cheyenne
- [x] Discover
- [x] Orion
- [x] S3 (us-east-1)
- [x] S3 (us-east-2)
- [x] S4

---

@BenjaminRuston commented on [Wed Mar 22 2023](https://github.com/JCSDA-internal/r2d2-data/issues/38#issuecomment-1479557538)

@ericlingerfelt please double check and assign to an epic you feel is most correct

---

@ericlingerfelt commented on [Wed Mar 22 2023](https://github.com/JCSDA-internal/r2d2-data/issues/38#issuecomment-1479630493)

HI @BenjaminRuston, I just noticed that this issue was created in the `r2d2-data` repo. I don't think that is what you intended. Data ingest issues created here are for the addition of data to the tutorial for EWOK and not for ingest into a data store. Next time, please create the issue in the `r2d2-ingest` repo. Thank you!

**Comment by ericlingerfelt** [comment]
Ingest underway on Orion into `r2d2-archive-orion`.

**Comment by ericlingerfelt** [comment]
Hi All - This data has been ingested into `r2d2-archive-orion`. We need to test this data before syncing it to the rest of the archive data stores. Thanks!

**Comment by BenjaminRuston** [comment]
excellent thanks @ericlingerfelt
