### ISSUE TITLE
[Ingest] AQUA_MODIS Radiance data (Water leaving Radiance)

### ISSUE THREAD

**Issue by HamidehGMAO** [JCSDA-internal/r2d2-ingest#62]
## Ingest description

*(Instructions: Please provide values for the following entries.)*

Description: 

Data type : observation

Other metadata (_For example, 
provider: NASA
observation type: Radiance
AQUA_MODIS

## Date range

Start date: 20210801
End date: 20210831

and 

Start date: 20220215
End date: 20220315

## Source host and directory/bucket

Source host: 

Data store directory path or S3 bucket path (_with wildcards if needed_):

## Target data store type (select one)

- [x] archive
- [ ] experiments
- [ ] gfs ensemble
- [ ] other 
    - Please describe: 
    
## Data store checklist

Data copied into R2D2 on:

- [x] Cheyenne
- [x] Discover
- [x] Orion
- [x] S3 (us-east-1)
- [x] S3 (us-east-2)
- [x] S4

**Comment by HamidehGMAO** [comment]
@ericlingerfelt @climbfuji Is there any specific format we need to follow for the naming the obs? Also, I'm not sure how to copy data into R2D2 on discover. Is there any documentation for this? Thanks

**Comment by climbfuji** [comment]
@ericlingerfelt is out today and part of tomorrow. @fabiolrdiniz You've done this a million times, can you help please?

**Comment by fabiolrdiniz** [comment]
@HamidehGMAO, good point. Here we go... sorry for the big message.

There are no constraints in r2d2 for the naming of the observations. The users can choose whatever they want. However, I suggest reading what is below.

People were using the `sensor_platform` nomenclature (e.g., `amsua_n19`), which for your specific case would result in `modis_aqua`. BUT I just checked that the `modis_aqua` is being used for AOD assimilation (pl. see https://github.com/JCSDA-internal/skylab/blob/develop/obs/ufo/modis_aqua.yaml). However, looking closely into that file, we can see that what is actually being used is `modis_aqua_aod` for ewok/r2d2 purposes (pl. see https://github.com/JCSDA-internal/skylab/blob/051158d554c4344810ec446afc69d86e2330d279/obs/ufo/modis_aqua.yaml#L7).

Assuming your application is to use `brightnessTemperature` from `modis_aqua`, I'd suggest you:

- store your observations using `modis_aqua`;
- then we can rearrange the files inside the https://github.com/JCSDA-internal/skylab repo
- renaming the current `modis_aqua` to `modis_aqua_aod` (with adjustments to the experiments using them)
- and adding your `modis_aqua` config for `brightnessTemperature` assimilation (similar to the others) there.

So, according to the current description of this issue, you would need to set `observation_type = modis_aqua` and `provider = nasa`.

**Comment by fabiolrdiniz** [comment]
Oh, I missed an answer regarding the store part... Here we go again...

You can find an example to store observations in the r2d2 tutorial document: https://github.com/JCSDA-internal/r2d2/blob/91f110b376b3ca7c89e0379c9f9a36bbc94d9c80/TUTORIAL.md#store

The above should be sufficient to start playing with that. If you are interested in checking how ewok does that inside its tasks, you can have a look here: https://github.com/JCSDA-internal/ewok/blob/d4af56802c6ba10c40ff43fc617e913457b79396/src/runtime/storeObservationsRun.py#L38-L46.

**Comment by BenjaminRuston** [comment]
thanks @fabiolrdiniz we likely need a few more details on what product is being pulled if it is indeed the L1B calibrated brightness temperature we should use that name, but if it's another project we may want to reconsider.

What is the specific MODIS product @HamidehGMAO ?
Is it in this list:
https://www.earthdata.nasa.gov/learn/find-data/near-real-time/modis#ed-modis-c61



The `provider` is that field we need to update at some point it does make sense to use `nasa` but that is a keyword that we really need to change as you can get that same data often from many sources so from a number of *providers* and as you know we've been using that to discriminate data for Skylab small with `coarseSampling`

but let's sort out what data is being added, as well though we should modify the existing `modis_aqua` to be `modis_aqua_aod` where needed as it is specifically that product

**Comment by climbfuji** [comment]
Thanks @fabiolrdiniz and @BenjaminRuston for helping out

**Comment by HamidehGMAO** [comment]
Thanks @fabiolrdiniz and @BenjaminRuston for the information. I appreciate it. I grab the data from https://oceandata.sci.gsfc.nasa.gov/directdataaccess/Level-2/Aqua-MODIS/year/day/ AQUA_MODIS.***.L2.OC.nc. and it is basically modis ocean color data which contain the remote sensing reflectance data and I calculate Water leaving radiance from the remote sensing reflectance data.

**Comment by BenjaminRuston** [comment]
OK so this is a level2 product and we should likely label it:
`modis_aqua_oc` or more verbosely `modis_aqua_ocean_color` so stick with the name of the product for the what is saved

are there future plans then to move to a `L1B` product at some point?  is this in the daytime so is the radiance a combination of emission and reflectance?

**Comment by HamidehGMAO** [comment]
@BenjaminRuston thanks for the clarification. Well, Actually I was thinking at the beginning to use the L1B product, but L1B just contain the top of the atmosphere radiance, and the issue is, OASIM doesn't simulate the top of the atmosphere radiance, and it just simulate the water leaving radiances. Until we figure it out how to simulate the top of the atmosphere for ocean color radiance data, we are going to use L2 data.

**Comment by travissluka** [comment]
@BenjaminRuston This is one of the side topics I want to talk about at the next quarterly relaunch since @HamidehGMAO will be in Boulder for that one: what do we need to do to go from L2 to L1? I would like for it to be a task for next aop year.

**Comment by ericlingerfelt** [comment]
Hi All - I am getting caught up here. Have these observations been stored in `r2d2-experiments-discover` yet? Do we have a list of indices returned by `store` (this is not entirely necessary)?

**Comment by ericlingerfelt** [comment]
Hi All - Is this for release 6 or 7?

**Comment by travissluka** [comment]
> Hi @travissluka, Is there a justification for including observations now that will not be used until release 7?

@ericlingerfelt it was on the AOP (OBSPROC-92.2) to have this in for release 6. for release 7 there are several tasks planned (e.g. TECHX-15.1) that are working on the coupled hofx that will need these obs already in r2d2

**Comment by HamidehGMAO** [comment]
Hi @ericlingerfelt. I was able to put the the data on the r2d2-experiments-discover. the indices for the Start date: 20210801 to End date: 20210831 are (17545.nc to 17576.nc) and for the  Start date: 20220215 to End date: 20220315 are (17577.nc to 17606.nc)

**Comment by ericlingerfelt** [comment]
Thank you!

**Comment by HamidehGMAO** [comment]
Hi @ericlingerfelt! I was wondering if this issue can be closed before the quarterly review? Is there anything we need to do? Thanks

**Comment by ericlingerfelt** [comment]
Hi @HamidehGMAO, We should absolutely be able to get this in by the quarterly review. I should have all of the information I need. Thanks!

**Comment by HamidehGMAO** [comment]
Sounds Good! Thanks @ericlingerfelt !

**Comment by ericlingerfelt** [comment]
Hi @HamidehGMAO, This issue is in progress and the data has been moved into the `r2d2-archive-discover` data store. Unfortunately, The `r2d2-experiments-discover` data store was not properly initialized and the `observation` directory there was created and is owned by the user `hebrahi1`. Is that you? If so, would you mind logging into Discover and execute the following commands? I will re-create the `observation` folder using the correct _jedipara_ role account when you are finished. Thank you! 

```
cd /discover/nobackup/projects/jcsda/s2127/r2d2-experiments-discover
rm -Rf observation
```

**Comment by HamidehGMAO** [comment]
Hi Eric! Yes. It's me. I will take care of it. Thanks

**Comment by HamidehGMAO** [comment]
Hi @ericlingerfelt,  "> find observation/ -type f | wc -l " returned 0 and I just removed the observation directory. Please let me Know if there is anything else I need to do. Thanks

**Comment by ericlingerfelt** [comment]
Thank you, @HamidehGMAO! I got that fixed.

**Comment by ericlingerfelt** [comment]
In progress in Orion and then Cheyenne and S4.

**Comment by ericlingerfelt** [comment]
Waiting on S4 (slow).

**Comment by ericlingerfelt** [comment]
Complete.
