### ISSUE TITLE
[Ingest] High res GEOS-CF backgrounds

### ISSUE THREAD

**Issue by jeromebarre** [JCSDA-internal/r2d2-ingest#64]
## Ingest description

See scripts PR for details:
https://github.com/JCSDA-internal/r2d2-ingest/pull/63
The yaml has the correct details

```
start: 2021080100
end: 2021081100
source_steps:
    - PT3H
    - PT4H
    - PT5H
    - PT6H
    - PT7H
    - PT8H
    - PT9H
window_length: PT6H
item: forecast
source_dir: /work/noaa/da/barre/geos_cf_sg
file_type: bkg
type: fc
model: geos_cf
experiment: oper
resolution: c540 **AND** c540r25conus
```

Note source dir is on Orion

## Target data store type (select one)

- [x] archive
- [ ] experiments
- [ ] gfs ensemble
- [ ] other 
    - Please describe:

## Data store checklist

Data copied into R2D2 on:

- [x] Cheyenne
- [x] Discover
- [x] Orion
- [x] S3 (us-east-1)
- [x] S3 (us-east-2)
- [ ] S4

**Comment by jeromebarre** [comment]
I just received the new runs with stretched grid. I will have them ingested in R2D2 by the end of today. Thanks for your patience.

**Comment by jeromebarre** [comment]
I will add an additional request for the stretched grid. I just need to test a cycle in skylab and put them on R2D2.

**Comment by ericlingerfelt** [comment]
OK. Thanks. How long will the additional ingest request take to be ready?

**Comment by jeromebarre** [comment]
a few hours.

**Comment by ericlingerfelt** [comment]
Great!

**Comment by jeromebarre** [comment]
I just had the `c540` ingested see`/home/barre/ingest_c540` the stretch grid backgrounds `c540r25conus` are still being processed. It will finish in an hour or so.

**Comment by jeromebarre** [comment]
The stretch grid is also now ingested on Orion. See script output at `/home/barre/ingest_c540r25conus`. Thanks for your patience!!!

**Comment by ericlingerfelt** [comment]
In progress on Orion.

**Comment by ericlingerfelt** [comment]
I can access now. Thanks!

**Comment by ericlingerfelt** [comment]
Underway on Orion.

**Comment by ericlingerfelt** [comment]
Completed on Orion. Starting sync.

**Comment by ericlingerfelt** [comment]
Waiting on Cheyenne and S4.

**Comment by ericlingerfelt** [comment]
Waiting on S4 (really slow with large files).

**Comment by ericlingerfelt** [comment]
Done.
