### ISSUE TITLE
[Ingest] static stdev B matrix file for GEOS-CF high res

### ISSUE THREAD

**Issue by jeromebarre** [JCSDA-internal/r2d2-ingest#65]
## Ingest description

static stdev B matrix file for GEOS-CF high res

Description: 

Data type: static B file

## Source host and directory/bucket

Source host: Orion

Data store directory path or S3 bucket path (_with wildcards if needed_):
`/work/noaa/da/barre/staticb_compo/skylab-6.0.0/geos_cf/c540/var_2021080100-2021081018/stddev.nc`

## Target data store type (select one)

- [ ] archive
- [ ] experiments
- [ ] gfs ensemble
- [x] other 
    - Please describe: static

## Data store checklist

Data copied into R2D2 on:

- [x] Cheyenne
- [x] Discover
- [x] Orion
- [x] S3 (us-east-1)
- [x] S3 (us-east-2)
- [x] S4

**Comment by ericlingerfelt** [comment]
Waiting on s4 (slow) and us-east-2.

**Comment by ericlingerfelt** [comment]
us-east-2 complete.
