### ISSUE TITLE
[Ingest] addition of AVHRR data

### ISSUE THREAD

**Issue by HamidehGMAO** [JCSDA-internal/r2d2-ingest#67]
## Ingest description
we are planning to add AVHRR data to r2d2

Description:

Provider: noaa
Observation_type: radiance (this needs to change)

Data type:
observation

## Date range

Start date: 01Aug2021

End date: 01Sep2021

## Source host and directory/bucket

Source host: 

Data store directory path or S3 bucket path (_with wildcards if needed_):

## Target data store type (select one)

- [x] archive
- [ ] experiments
- [ ] gfs ensemble
- [ ] other 
    - Please describe: 

## Data store checklist

Data copied into R2D2 on:

- [x] Cheyenne
- [x] Discover
- [x] Orion
- [x] S3 (us-east-1)
- [x] S3 (us-east-2)
- [x] S4

**Comment by HamidehGMAO** [comment]
@BenjaminRuston Do you know if anyone has been working on adding the AVHRR or VIRRS to r2d2? If not, Any suggestion on which source of data we need to use? Thanks

**Comment by HamidehGMAO** [comment]
Hi @BenjaminRuston and @huishao-r,  Do you know if anyone has been working on adding the AVHRR or VIRRS to r2d2? If not, Any suggestion on which source of data we need to use? Thanks.

**Comment by HamidehGMAO** [comment]
Hi @danholdaway and @frolovsa, we have been talking about this issue with @BenjaminRuston last week, and he suggested asking you guys, what is your suggestion on which source of data for AVHRR and VIRRS radiance we need to add to Skylab? Thanks.

**Comment by danholdaway** [comment]
@HamidehGMAO I don't have an opinion about what gets added to skylab so whichever makes sense to you.

**Comment by HamidehGMAO** [comment]
@danholdaway Thanks for your reply. OK. Do you know which dataset is used in GMAO?

**Comment by danholdaway** [comment]
I don't, but tagging @gmao-wgu in case he is aware.

**Comment by HamidehGMAO** [comment]
Hi @ericlingerfelt and @cmgas. just a quick question. Do you guys prepare the obs for each 24 hrs of data in each file or 6hrs. Thanks

**Comment by HamidehGMAO** [comment]
Hi @ericlingerfelt. I have stored the avhhr data to the r2d2-experiments-discover, the index numbers are 18153.nc to 18184.nc. Please let me know if you need any more information. Thanks

**Comment by HamidehGMAO** [comment]
Just for the record, this is the AVHRR data on METOP-A, NOAA15, NOAA18 and NOAA19 satellites.

**Comment by cmgas** [comment]
@HamidehGMAO we do 6hrs file for now

**Comment by ericlingerfelt** [comment]
@climbfuji, Not yet, but it can be prioritized to be done during the final steps of the compute host rollout.

**Comment by HamidehGMAO** [comment]
Hi @climbfuji, We'd like to have this in the upcoming release if it's possible.

**Comment by ericlingerfelt** [comment]
Hi All - So the `avhhr` data are under index numbers are 18153 to 18184. What about the `virrs` data? Is this also in `r2d2-experiments-nccs`?

**Comment by ericlingerfelt** [comment]
Should we open a new issue for virrs and just leave this one for the avhhr data?

**Comment by ericlingerfelt** [comment]
Hi @HamidehGMAO, I can only transfer the data from the experiments data stores for the other read-only data stores. I am unable to check the indices or other metadata you provide. You can use R2D2's Python API to investigate the results of your data ingest. I am happy to assist you with using R2D2's functions if you run into any problems. Thanks!

**Comment by ericlingerfelt** [comment]
For now, I will complete the transfer of observation indices 18153 to 18184 for now.

**Comment by HamidehGMAO** [comment]
OK, Thanks for doing that. I will double check on indices.

**Comment by ericlingerfelt** [comment]
So I searched for one of your indices: 18153 and received this output. You may want to reconsider using 'radiance', as the `observation_type`. This `observation_type` indicates nothing in regards to the platform or sensor ("AVHRR"). 

```
>>> R2D2Data.search(item='observation', observation_index=)
[{'observation_index': 18153, 'provider': 'noaa', 'observation_type': 'radiance', 'file_extension': 'nc', 'window_start': datetime.datetime(2021, 8, 24, 0, 0), 'window_length': 'PT24H', 'create_date': datetime.datetime(2023, 11, 18, 3, 14, 5), 'mod_date': datetime.datetime(2023, 11, 18, 3, 14, 5)}]
```

**Comment by HamidehGMAO** [comment]
Hmm, So what is your suggestion? using "AVHRR radiance" as obs type? or should I add the satellite name as well like "AVHRR metop-A radiance"?

**Comment by ericlingerfelt** [comment]
Look at https://github.com/JCSDA-internal/r2d2-ingest/issues/79. I am not qualified to label your data. But all observation_type values should be lower case with an underscore delimiter.

**Comment by HamidehGMAO** [comment]
OK, Thanks. I will take a look.

**Comment by ericlingerfelt** [comment]
We can update the `observation_type` at any time.

**Comment by ericlingerfelt** [comment]
Done.
