### ISSUE TITLE
[Ingest] geos crtm.bkg static files

### ISSUE THREAD

**Issue by jeromebarre** [JCSDA-internal/r2d2-ingest#68]
## Ingest description

Put static crtm files for geos DA in static directories

Description: 

Data type (_For example, observation, forecast_): static backgrounds

Other metadata (_For example, provider, observation type, model_): 

## Date range

Start date: N/A

End date: N/A

## Source host and directory/bucket

Source host: discover

Data store directory path or S3 bucket path (_with wildcards if needed_): 
/discover/nobackup/drholdaw/SwellStaticFiles/jedi/interfaces/geos_atmosphere/GEOS_CRTM_Surface

files:
geos.crtmsrf.c[12,24,48,90,180,360,720].nc4

## Target data store type (select one)

- [ ] archive
- [ ] experiments
- [ ] gfs ensemble
- [x] other 
    - Please describe:  static

## Data store checklist

Data copied into R2D2 on:

- [ ] Cheyenne
- [x] Discover
- [x] Orion
- [x] S3 (us-east-1)
- [x] S3 (us-east-2)
- [x] S4
- [x] AWS ParallelCluster
- [x] NOAA Parallelworks AWS
- [x] NOAA Parallelworks Azure
- [x] NOAA Parallelworks Gcloud

**Comment by jeromebarre** [comment]
What is the status of this? Why has this been removed from sprints? Thanks!

**Comment by climbfuji** [comment]
This is the third week of the tech debt sprint, we were supposed to focus on reducing technical debt, therefore this is going to be worked on in the next weeks.

**Comment by ericlingerfelt** [comment]
This issue did not list any dependencies or other blocking issues. It also did not have an `INGEST` GitHub label for filtering.

**Comment by climbfuji** [comment]
It's Friday noon ET nobody's going to die if this gets worked on next week Monday. Also, we are working at 100% if not more. This PR will be worked on as soon as possible without having to work overtime on weekends.

**Comment by jeromebarre** [comment]
That's ok, just making sure this is not forgotten.

**Comment by jeromebarre** [comment]
But I don't think copying a few files to the static dir should be such a huge hassle though...

**Comment by ericlingerfelt** [comment]
Where in the static skylab-7 directory would you like these placed and what subdirectories do you want to use? We do not have this information.

**Comment by jeromebarre** [comment]
something like `skylab-*/geos/crtmsrf/`

**Comment by climbfuji** [comment]
I started creating the static data set skylab-7.0.0 from skylab-6.0.0 on Discover, will add the new geos static data and then sync to the other platforms.

**Comment by ericlingerfelt** [comment]
Thanks, @climbfuji!

**Comment by climbfuji** [comment]
@jeromebarre @ericlingerfelt The new static data set skylab-7.0.0 is now available on Discover, Orion, S4, us-east-1 and us-east-2.

Cheyenne and all other infrastructure at that center are currently offline for maintenance, therefore we need to keep this issue open until that's done.

**Comment by climbfuji** [comment]
@jeromebarre Which of these files would you like to have in the static-data git repo?

**Comment by climbfuji** [comment]
@ericlingerfelt Note that the template is missing the following platforms:
- [ ] AWS ParallelCluster
- [ ] NOAA Parallelworks AWS
- [ ] NOAA Parallelworks Azure
- [ ] NOAA Parallelworks Gcloud

**Comment by climbfuji** [comment]
static-data PR and skylab-PR that go along with this issue (creating of v7 static data sets, addition of above files):

https://github.com/JCSDA-internal/static-data/pull/7
https://github.com/JCSDA-internal/skylab/pull/181

**Comment by climbfuji** [comment]
Only Cheyenne is missing.

**Comment by jeromebarre** [comment]
Thanks @climbfuji

**Comment by climbfuji** [comment]
Cheyenne is done, closing.
