### ISSUE TITLE
[Ingest] ensemble and control for 4denvar experiment

### ISSUE THREAD

**Issue by cmgas** [JCSDA-internal/r2d2-ingest#69]
## Ingest description

Data type: forecast (pt3h, pt6h and pt9h)

All the data is stored on pcluster and I would like to just _rename_ the expid and DB, is it possible?
I checked and these expids currently contain only and all of what I need ingested.

- ensemble members 0-25 currently under expid `86d563`
- control currently under expid `8eef01`

I would like them to be stored under `oper`, which will overwrite some data but we're ok with it (@shlyaeva , @ytremolet )

Control data copied into R2D2 on:

- [x] Cheyenne
- [x] Discover
- [x] Orion
- [x] S3 (us-east-1)
- [x] S3 (us-east-2)
- [x] S4

Ensemble data copied into R2D2 on:

- [x] Orion
- [x] S3 (us-east-1)
- [x] S3 (us-east-2)
- [x] S4

**Comment by ericlingerfelt** [comment]
In progress. This will take longer since this task is the first to sync data from RND to the other data stores.

**Comment by ericlingerfelt** [comment]
Currently moving `8eef01` to `oper` in `r2d2-archive-us-east-2`.

**Comment by ericlingerfelt** [comment]
Move of `8eef01` to `oper` in `r2d2-archive-us-east-2` complete.

**Comment by ericlingerfelt** [comment]
FYI: Note that the move of `86d563` to `oper` in `r2d2-gfsensemble-us-east-2` will take a little while given the number of files involved.

**Comment by ericlingerfelt** [comment]
Move of `86d563` to `oper` in `r2d2-archive-us-east-2` complete.

**Comment by ericlingerfelt** [comment]
Starting work syncing data stores globally.

**Comment by ericlingerfelt** [comment]
Syncing both experiments from `us-east-2` to `orion`.

**Comment by ericlingerfelt** [comment]
Waiting on `gfsensemble` sync for us-east-1 and s4.

**Comment by ericlingerfelt** [comment]
Waiting on gfsensemble sync on s4.

**Comment by ericlingerfelt** [comment]
Still running on s4 (slow).

**Comment by ericlingerfelt** [comment]
Complete.
