### ISSUE TITLE
[Ingest]  Eliminate some bad GOES-17 data files from our "golden months" as there were clear instrument problems

### ISSUE THREAD

**Issue by gthompsnJCSDA** [JCSDA-internal/r2d2-ingest#71]
## Ingest description

There are some bad data files from GOES-17 that need to be removed from our golden months archives.  The original full-res data from AWS s3 buckets was re-checked in 3-hour increments for 2021Aug01-31 and 2022Feb15-Mar15.  Some 3-hourly files show complete or partial scans with bad data in water vapor channels 8, 9, and 10.  In order to keep Skylab experiments running smoothly, we need to eliminate the bad data and put into place the empty placeholder file for the specific corrupted data times.

Mostly 1200 and 1500 UTC times are affected, but very often the `DQF` (data quality flags) are properly set to declare the data are bad.  Under those conditions, the data will be rejected easily with the PreQC check.  So the times that have all bad data but are well indicated using the DQF variable are left in place (which is all of Aug2021).

The screen capture before shows an example of the problem. The circular images are direct L1b radiances at 21, 18, 15, 12, 3, and 0z (top-to-bottom and 6 and 9z are missing because it was the "spring eclipse" times).

![GOES17_bad_examples](https://github.com/JCSDA-internal/r2d2-ingest/assets/63315545/6e9ae129-7f6d-4488-8e6c-8d4edd6ffe69)

Data type:  Observation

Other metadata:  GOES-17 from NOAA originally 

## Date range

Problematic files are somewhat sporadic except for the 1500 UTC times which are all bad from 15Feb to 05Mar2022.  The list of bad file index references from `archive-orion` is the following: 7334, 5521, 7306, 4473, 4608, 6169, 7786, 5901, 4822, 11049, 4933, 9261, 7479, 7453, 7386, 6517, 6036, 8075, 4450, 6105, 6902

## Source host and directory/bucket

Source host:  TBD

Data store directory path or S3 bucket path (_with wildcards if needed_):

## Target data store type (select one)

- [x] archive
- [ ] experiments
- [ ] gfs ensemble
- [ ] other 
    - Please describe: 

## Data store checklist

Data copied into R2D2 on:

- [x] Cheyenne
- [x] Discover
- [x] Orion
- [x] S3 (us-east-1)
- [x] S3 (us-east-2)
- [x] S4

**Comment by symoore90** [comment]
is this apart of the technical debt sprint? @gthompsnJCSDA @ericlingerfelt

**Comment by ericlingerfelt** [comment]
HI @symoore90, I would not consider this issue part of the technical debt sprint, but @gthompsnJCSDA may think differently.

**Comment by ericlingerfelt** [comment]
I'll try to get to this shortly. Thanks guys!

**Comment by ericlingerfelt** [comment]
From @gthompsnJCSDA on Slack, The empty file is at `/work2/noaa/jcsda/gthompsn/jedi/empty.nc4`.

**Comment by ericlingerfelt** [comment]
Complete on Orion.

**Comment by gthompsnJCSDA** [comment]
> Complete on Orion.

I will give my skylab exp another attempt now that this is fixed on Orion. Will be cool to see if it fixes what I was finding (it should result in correct fix).

**Comment by gthompsnJCSDA** [comment]
I can confirm that substituting the bad files with the empty file allowed my Skylab experiment to work like it should!  Yeah!!  Thanks Eric!

**Comment by ericlingerfelt** [comment]
All done except S4.

**Comment by ericlingerfelt** [comment]
Done.

**Comment by fabiolrdiniz** [comment]
Do we know how many of these indices are within the 00Z Feb 15 2022 and 18Z Feb 17 2022 period? We'll need to update r2d2-data accordingly.

**Comment by ericlingerfelt** [comment]
Thanks, @fabiolrdiniz, for thinking of the need for an r2d2-data issue as well.

**Comment by gthompsnJCSDA** [comment]
I will check which of the smaller files in r2d2-data will need to be changed; stay tuned.

Meanwhile, my glimpse at index number 9563 which refers to 2022-02-16T03:00:00Z original GOES file shows the data are all fine.  So the crash in Skylab experiment might not be due to bad data since these data are good.  I need to keep investigating.  So, I recommend we keep this issue closed until I know for sure anything is wrong with the GOES17 data in `r2d2-archive-`*

**Comment by gthompsnJCSDA** [comment]
I found and fixed the files in `r2d2-data` which are index numbers: 1276, 1191, and 1576.  I will have a pull request prepared in just a minute for the other repo.

**Comment by ericlingerfelt** [comment]
Great, @gthompsnJCSDA. Please let us know when it is ready for review.
