### ISSUE TITLE
Rest of ensemble of s3 for 4denvar experiment

### ISSUE THREAD

**Issue by cmgas** [JCSDA-internal/r2d2-ingest#73]
## Description

We need to pull the members 26 to 80 on s3 (on gaussian grid) so we can run the 4denvar experiment like in oper system. 
This is the sequel to this issue: https://github.com/JCSDA-internal/r2d2-ingest/issues/56

- [x] fetch `atmf` files from HPSS on Hera (@climbfuji)
- [x] fetch `sfcf` files from HPSS on Hera (@climbfuji)
- [x] transfer `atmf` files to S3 bucket in AWS USAF us-east-2 `s3://ingest-hpss/gdas/` (@climbfuji)
- [x] transfer `sfcf` files to S3 bucket in AWS USAF us-east-2 `s3://ingest-hpss/gdas/` (@climbfuji)
- [x] download gdas data to AWS parallel cluster or implement direct access in conversion workflow (@cmgas, @ashley314)
- [x] convert to desired resolution and format using UFS_UTILS on AWS parallel cluster (@cmgas, @ashley314)
- [x] convert from coldstart to warmstart with the ufs-weather-model (@cmgas) 
- [x] store in local r2d2 data store (@cmgas) 
- [x] transfer back to Orion to run cost estimate experiments there (12Tb of data; @climbfuji)
- [x] ingest in local experiment database for initial experiments to determine runtime stats/costs and definition of final experiment (@cmgas)
- [x] ingest in authoritative database (@ericlingerfelt) - for this we need runtime stats/costs and then a decision on how the final experiment will look like
- [x] Delete original data (only the model data, not the fixed data) from `ingest-hpss` bucket (@climbfuji)

**Comment by climbfuji** [comment]
I'm on it!

**Comment by climbfuji** [comment]
@cmgas The data should all be on the S3 bucket, can you check if it's what you want please?

**Comment by climbfuji** [comment]
@cmgas is the step "ingest in local experiment database for initial experiments to determine runtime stats/costs and definition of final experiment" done?

**Comment by climbfuji** [comment]
I haven't yet - will do later today and then close the issue. Thanks!

**Comment by climbfuji** [comment]
> @climbfuji can we close this if you have deleted the files from hpss?

Done!
