### ISSUE TITLE
[Ingest] GEOS C90 single member bkgs

### ISSUE THREAD

**Issue by jeromebarre** [JCSDA-internal/r2d2-ingest#74]
## Ingest description

*(Instructions: Please provide values for the following entries.)*

Description:  Ingest for single member GEOS (non-ensemble)

Data type (_For example, observation, forecast_): forecast

Other metadata (_For example, provider, observation type, model_): GEOS model

## Date range
```
start: 2021080500
end: 2021081200
type: fc
model: geos
experiment: geos_control_member
resolution: c90
```

## Source host and directory/bucket

Source host:  discover

Data store directory path or S3 bucket path (_with wildcards if needed_):

## Target data store type (select one)

- [x] archive
- [ ] experiments
- [ ] gfs ensemble
- [ ] other 
    - Please describe: 

## Data store checklist

Data copied into R2D2 on:

- [x] Cheyenne
- [x] Discover
- [x] Orion
- [x] S3 (us-east-1)
- [x] S3 (us-east-2)
- [ ] S4

**Comment by mer-a-o** [comment]
Thanks @jeromebarre for preparing the data. Yes, this works for me. @ericlingerfelt please go ahead and proceed when you have time. Thanks.

**Comment by ericlingerfelt** [comment]
Hi @jeromebarre, Did you export the indices by any chance? If not, no worries. I can do a search. Thanks.

**Comment by jeromebarre** [comment]
I unfortunately did not, but can rerun the scripts and store the output. Just let me know.

**Comment by ericlingerfelt** [comment]
Hi @jeromebarre, The issue states 'Source host: discover' but when I go to discover I receive the following error. I assume you meant 'Source host: orion'?

```
(venv) jedipara@discover11:/discover/nobackup/projects/jcsda/s2127> python3 
Python 3.9.7 (default, Sep 16 2021, 13:09:58) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from r2d2.util.admin_util import AdminUtil
>>> AdminUtil.move_experiment(source_experiment='geos_control_member', target_experiment='oper')
2023-11-02 10:34:36,184 - INFO - r2d2.r2d2_index - Using eric2 as the user
2023-11-02 10:34:36,236 - INFO - r2d2.r2d2_index - Using discover as the host
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/gpfsm/dnb33/elingerf/jedi/jedi-bundle/r2d2/src/r2d2/util/admin_util.py", line 49, in move_experiment
    raise err.GenericError(f'The experiment {source_experiment} was executed using '
r2d2.error.GenericError.GenericError: The experiment geos_control_member was executed using the host orion.
```

**Comment by jeromebarre** [comment]
I am on discover and for example if I do a search it returns something:
```
>>> R2D2Data.search(resolution='c90', item='forecast', date=datetime.datetime(2021, 8, 5, 0, 0), step='PT3H',model='geos', experiment='geos_control_member')
[{'forecast_index': 2236825, 'model': 'geos', 'experiment': 'geos_control_member', 'file_extension': 'nc', 'resolution': 'c90', 'domain': '', 'file_type': 'bkg_clcv', 'step': 'PT3H', 'tile': -9999, 'member': -9999, 'date': datetime.datetime(2021, 8, 5, 0, 0), 'create_date': datetime.datetime(2023, 11, 1, 16, 10, 46), 'mod_date': datetime.datetime(2023, 11, 1, 16, 10, 46)}, {'forecast_index': 2237200, 'model': 'geos', 'experiment': 'geos_control_member', 'file_extension': 'nc', 'resolution': 'c90', 'domain': '', 'file_type': 'abkg.eta', 'step': 'PT3H', 'tile': -9999, 'member': -9999, 'date': datetime.datetime(2021, 8, 5, 0, 0), 'create_date': datetime.datetime(2023, 11, 1, 16, 29, 11), 'mod_date': datetime.datetime(2023, 11, 1, 16, 29, 11)}]
```

**Comment by ericlingerfelt** [comment]
`R2D2Data.search` only returns the metadata record and indicates that _**somewhere**_ there exists a data file in a data store. Please use `R2D2Data.find_by_index` to get a list of data stores where a data file linked to the metadata record exists. 

https://github.com/JCSDA-internal/r2d2/blob/develop/TUTORIAL.md#find_by_index

The README entry for `R2D2Data.search` is slightly incorrect now and needs to be updated.

**Comment by ericlingerfelt** [comment]
It appears from the database that `$R2D2_HOST='orion'` was set for this experiment and not 'discover'. I'll update that directly in the database and proceed.

**Comment by jeromebarre** [comment]
oops sorry... let me know if you need further clarifications on this.

**Comment by ericlingerfelt** [comment]
The data is registered to Discover, but the experiment is listed as Orion. I'll just change the experiment to Discover.

**Comment by ericlingerfelt** [comment]
I think in order for this to happen, the experiment 'geos_control_member' was registered on Orion, but the data was ingested on Discover.

**Comment by ericlingerfelt** [comment]
In progress on Discover.

**Comment by ericlingerfelt** [comment]
Waiting on S4 (slow).

**Comment by ericlingerfelt** [comment]
Done.
