### ISSUE TITLE
[Ingest] MPAS ensemble and high res files

### ISSUE THREAD

**Issue by cmgas** [JCSDA-internal/r2d2-ingest#78]
## Ingest description

Ensemble data is currently on pcluster under the expid `4be898`. This was a `debug` experiment, could you at least move it to `science` so it doesn't disappear soon?

High res data is on pcluster under the expid `4denvar_mpas`. This expid also contains other files that I do not need, but they are at other resolutions. If you serach for expid 4denvar_mpas at the resolution 15-3km, these are all the files are need: following forecast indexes 15-3km:  [2338087 2338120 2338146 2338147 2338148 2338149 2379854]

They are the MPAS equivalent to the UFS ensemble data we ingested recently. 

Thank you

## Target data store type for `4denvar_mpas`

- [x] archive
- [ ] experiments
- [ ] gfsensemble
- [ ] geosensemble
- [ ] other 
    - Please describe: mpasensemble

## Data ingest for `4denvar_mpas` processing checklist for the R2D2 Administrator

Data has been ingested into the target data store type on the following data hubs:

- [x] Casper/Derecho (NCAR-Wyoming Supercomputing Center)
- [x] Discover (NASA Center for Climate Simulation)
- [x] Orion/Hercules (Mississippi State University High Performance Computing) [UNDERWAY]
- [x] S3 (jcsda-noaa-aws-us-east-1)
- [x] S3 (jcsda-usaf-aws-us-east-2)
- [x] S4 (Space Science and Engineering Center)

## Target data store type for `4be898`

- [ ] archive
- [ ] experiments
- [ ] gfsensemble
- [ ] geosensemble
- [x] other 
    - Please describe: mpasensemble

## Data ingest for `4be898` processing checklist for the R2D2 Administrator

Data has been ingested into the target data store type on the following data hubs:

- [x] Orion/Hercules (Mississippi State University High Performance Computing) [UNDERWAY]
- [x] S3 (jcsda-usaf-aws-us-east-2)

**Comment by climbfuji** [comment]
@cmgas @ericlingerfelt What is the status of this?

**Comment by ericlingerfelt** [comment]
Set to "science".

**Comment by climbfuji** [comment]
@cmgas Is this issue resolved or do we need to do more to resolve it?

**Comment by climbfuji** [comment]
> @climbfuji, We still need to think about whether we want to use `mpasensemble` or just `archive` for storage and then actually ingest the data.

Got it, thanks.

**Comment by ericlingerfelt** [comment]
Is this data only 7 files?

**Comment by cmgas** [comment]
Yes!

**Comment by ericlingerfelt** [comment]
All deterministic?

**Comment by ericlingerfelt** [comment]
I'm confused because the description and title mention ensemble data.

**Comment by ericlingerfelt** [comment]
`4be898` goes into `mpasensemble` and `4denvar_mpas` goes into `archive`?

**Comment by cmgas** [comment]
> `4be898` goes into `mpasensemble` and `4denvar_mpas` goes into `archive`?


All of 4be898 goes in mpasensemble, they are ensemble files

The 7 files I detailed from 4denvar_mpas go in archive, they are deterministic files

**Comment by ericlingerfelt** [comment]
Thank you, @cmgas!

**Comment by ericlingerfelt** [comment]
A side note, @cmgas, in the future please create a separate issue for deterministic and ensemble data files since they will be stored in different data stores. This ingest issue is really two ingest issues. Thanks!

**Comment by ericlingerfelt** [comment]
Done.
