### ISSUE TITLE
[Ingest] Adding AVHRR and VIIRS SST observations

### ISSUE THREAD

**Issue by kbhargava** [JCSDA-internal/r2d2-ingest#79]
## Ingest description

Data ingest request for AVHRR and VIIRS SST superobbed 10 minute data

Description: 

Data type : Observations

Other metadata (_For example, provider, observation type, model_): 
Observation types:
1. AVHRRR SST platforms: Metop B through C
sst_avhrr_metop-b.yaml
sst_avhrr_metop-c.yaml
2. VIIRS SST platforms: Suomi-NPP (Suomi National Polar-orbiting Partnership) and JPSS-1 (Joint Polar Satellite System-1)/NOAA-20
sst_viirs_n20.yaml
sst_viirs_npp.yaml
Provider would be:
noaa_so025

Timeline (_When does this issue need to be completed_): December 2023, hopefully!

## Date range

Start date: 20220215

End date: 20220315

## Source host and directory/bucket

Source host: orion

## Target data store type (select one)

- [x] archive
- [ ] experiments
- [ ] gfs ensemble
- [ ] other 
    - Please describe: 

## Data store checklist

Data copied into R2D2 on:

- [x] Cheyenne
- [x] Discover
- [x] Orion
- [x] S3 (us-east-1)
- [x] S3 (us-east-2)
- [x] S4

**Comment by climbfuji** [comment]
@kbhargava Can you please assign this to the correct epic?

@ericlingerfelt Note that this is needed within this month (thanks Kriti for answering the new question in the template). I'll add it to the next sprint, but it may slip to the week of Dec 25.

**Comment by kbhargava** [comment]
> @kbhargava Can you please assign this to the correct epic?
> 
> @ericlingerfelt Note that this is needed within this month (thanks Kriti for answering the new question in the template). I'll add it to the next sprint, but it may slip to the week of Dec 25.

done!

**Comment by kbhargava** [comment]
I am done moving the files to `/work2/noaa/da/jedipara/r2d2-experiments-msu/observation` . There are a few missing files. Do we keep a log of those somewhere?

**Comment by ericlingerfelt** [comment]
Hi @kbhargava, I need more information in order to process your files. In the description above, please include the `observation_type` and `provider` used when you stored these files.

**Comment by kbhargava** [comment]
The observation types include:
sst_avhrr_metop-b.yaml
sst_avhrr_metop-c.yaml
sst_viirs_n20.yaml
sst_viirs_npp.yaml
The provider is:
noaa_so025

Also updating the description.

**Comment by ericlingerfelt** [comment]
Thank you! I didn't want to guess that information.

**Comment by ericlingerfelt** [comment]
Underway on Orion.

**Comment by ericlingerfelt** [comment]
Hi @kbhargava, The ingest into Orion is still ongoing. I just checked and there are 16,246 observation data files in `r2d2-experiments-orion` that match the criteria in your description above. The files are every 10 minutes. Is this correct?

**Comment by kbhargava** [comment]
> Hi @kbhargava, The ingest into Orion is still ongoing. I just checked and there are 16,246 observation data files in `r2d2-experiments-orion` that match the criteria in your description above. The time interval is PT10M. Is this correct?

Yes!! That's correct. These are superobed files every 10 minutes. It's a lot. 😀

**Comment by ericlingerfelt** [comment]
Cool! No worries! We'll just let it crank away.

**Comment by ericlingerfelt** [comment]
Done on Orion. Starting sync jobs to other data hubs.

**Comment by ericlingerfelt** [comment]
Done.

**Comment by kbhargava** [comment]
> Done.

Thank you so much for all your help.
