### ISSUE TITLE
[Re-Ingest] Issues with 4denvar forecast data sets

### ISSUE THREAD

**Issue by ericlingerfelt** [JCSDA-internal/r2d2-ingest#80]
## Ingest description

Related to https://github.com/JCSDA-internal/r2d2/issues/501

## Removal data store type (select one)

- [ ] archive
- [ ] experiments
- [x] gfsensemble
- [ ] other 
    - Please describe: 

## Data store checklist

Data removed from R2D2 on:

- [x] Orion
- [x] S3 (us-east-1)
- [x] S3 (us-east-2)
- [x] S4

**Comment by cmgas** [comment]
Proposition for solving the current issue with 4denvar backgrounds:
- List of indices to remove entirely from ALL platforms: 
[to_remove.txt](https://github.com/JCSDA-internal/r2d2-ingest/files/13638936/to_remove.txt)

- List of indices to rename to a different experiment ID (these are on Orion and S3 only). Rename from `oper` to `oper4d`: 
[to_rename.txt](https://github.com/JCSDA-internal/r2d2-ingest/files/13638940/to_rename.txt)

**Comment by ericlingerfelt** [comment]
Thank you, @cmgas! I'm looking now.

**Comment by ericlingerfelt** [comment]
The rename is complete. Setting up the remove jobs on orion, s4, us-east-1, and us-east-2.

**Comment by ericlingerfelt** [comment]
Remove is underway on us-east-1 and us-east-2. I need to update my environment on S4 and get my new phone set up for orion.

**Comment by cmgas** [comment]
Was the rename also done for s3 data or is it not applicable?

**Comment by ericlingerfelt** [comment]
The rename was done for the metadata record describing the data file on disk **_wherever_** the file physically exists.

**Comment by ericlingerfelt** [comment]
The removal _**must**_ be done per platform.

**Comment by ericlingerfelt** [comment]
Started removal on Orion.

**Comment by ericlingerfelt** [comment]
Removed from Orion.

**Comment by ericlingerfelt** [comment]
Removed from S4. Issue complete.
