### ISSUE TITLE
localization files for GEOS aero + weather

### ISSUE THREAD

**Issue by jeromebarre** [JCSDA-internal/r2d2-ingest#81]
## Ingest description

ingest this `Orion:/work2/noaa/jcsda/barre/static/geos/localization/c90/nicas.nc`

into `<hpc jcsda dir>/static/skylab-7.0.0/geos/localization/c90/nicas.nc`

Description: 

Data type (_For example, observation, forecast_):

nicas files

Other metadata (_For example, provider, observation type, model_): geos

Timeline (_When does this issue need to be completed): before 12/15

## Date range

Start date: NA

End date: NA

## Source host and directory/bucket

Source host: Orion

Data store directory path or S3 bucket path (_with wildcards if needed_):

## Target data store type (select one)

- [ ] archive
- [ ] experiments
- [ ] gfs ensemble
- [x] other 
    - Please describe: static

## Data store checklist

Data copied into R2D2 on:

- [x] AWS ParallelCluster
- [x] Casper/Derecho
- [x] Discover
- [x] Orion/Hercules
- [x] S3 (us-east-1)
- [x] S3 (us-east-2)
- [x] S4

## Associated pull request in [r2d2/scripts](https://github.com/JCSDA-internal/r2d2/tree/develop/scripts) (if creating new ingestion scripts)

*(This instruction will change once we create the r2d2-ingest repository.)*

**Comment by jeromebarre** [comment]
hold on, on this request as a better solution with only one file that is not dependent on mpi layout has been proposed. Testing this now and will update this ingest request and likely remove the dependency with https://github.com/JCSDA-internal/skylab/pull/247

**Comment by jeromebarre** [comment]
It is now a single file, and can now be ingested.

**Comment by climbfuji** [comment]
I'll take care of that @ericlingerfelt. I should have done that together with Anna's localization ingest PR!

**Comment by climbfuji** [comment]
Completed

**Comment by ericlingerfelt** [comment]
Thanks, @climbfuji!

**Comment by jeromebarre** [comment]
Very sorry I have to reopen this issue as the file I generated was using the wrong branch and one variable group was missing. The correct file is in the same folder on Orion. 🙏🏻

**Comment by climbfuji** [comment]
got it, may take some time

**Comment by climbfuji** [comment]
reingest done (turned out I had most windows still open, therefore quick to do)

**Comment by jeromebarre** [comment]
thanks a lot
