### ISSUE TITLE
[Ingest] Localization files for GFS 4DEnVar experiments

### ISSUE THREAD

**Issue by shlyaeva** [JCSDA-internal/r2d2-ingest#82]
## Ingest description

Description: global NICAS files for GFS experiments localization

Data type: static data

Timeline: by the data freeze date for v7

## Source host and directory/bucket

Source host: orion
Data directory: /work2/noaa/jcsda/ashlyaev/jedi/static/skylab-7.0.0/ensb_localization/c384_explicit_lengthscale

## Target data store type (select one)

Static data in:
$(static_data)/skylab-7.0.0/ensb_localization/c384_explicit_lengthscale/

## Data store checklist

Data copied into R2D2 on:

- [x] AWS ParallelCluster
- [x] Casper/Derecho
- [x] Discover
- [x] Orion/Hercules
- [x] S3 (us-east-1)
- [x] S3 (us-east-2)
- [x] S4

**Comment by climbfuji** [comment]
Done

**Comment by shlyaeva** [comment]
Thank you!!!
