### ISSUE TITLE
[Ingest] Adding ADT observations for February March 2022

### ISSUE THREAD

**Issue by kbhargava** [JCSDA-internal/r2d2-ingest#83]
## Ingest description

*(Instructions: Please provide values for the following entries.)*

Description: 

Data type: observation

Other metadata:
**Provider ** : noaa
**Observation type:**

1. adt_3a : Sentinel-3A
2. adt_3b : Sentinal-3B
3. adt_6a : Sentinel-6A
4. adt_c2 : Cryosat-2
5. adt_j3 : JASON -3
6. adt_sa : SARAL

Timeline (_When does this issue need to be completed_): End of December/ January beginning, hopefully!

## Date range

Start date: 20220215

End date: 20220315

## Source host and data store

Source host: orion

## Target data store type (select one)

- [x] archive
- [ ] experiments
- [ ] gfsensemble
- [ ] geosensemble
- [ ] other 
    - Please describe: 

## Data ingest processing checklist for the R2D2 Administrator

Data has been ingested into the target data store type on the following data hubs:

- [ ] AWS ParallelCluster R&D
- [ ] Casper/Derecho (NCAR-Wyoming Supercomputing Center)
- [ ] Discover (NASA Center for Climate Simulation)
- [x] Orion/Hercules (Mississippi State University High Performance Computing)
- [ ] S3 (jcsda-noaa-aws-us-east-1)
- [ ] S3 (jcsda-usaf-aws-us-east-2)
- [ ] S4 (Space Science and Engineering Center)

**Comment by ericlingerfelt** [comment]
Done.
