### ISSUE TITLE
[Ingest] static files for MPAS higher resolutions

### ISSUE THREAD

**Issue by cmgas** [JCSDA-internal/r2d2-ingest#85]
## Ingest description

Files are in `/mnt/experiments-efs/clementine.gas/data_mpas/`
There are three: 
`/mnt/experiments-efs/clementine.gas/data_mpas/15-3km/static.6488066.nc`
`/mnt/experiments-efs/clementine.gas/data_mpas/30km/static.655362.nc`
`/mnt/experiments-efs/clementine.gas/data_mpas/60km/static.163842.nc`

They need to go in `$EWOK_STATIC_DATA/skylab-7.0.0/mpas`, each file under its own resolution.

**Comment by climbfuji** [comment]
Updated files are on:
- [ ] AWS ParallelCluster
- [ ] S3 us-east-1
- [ ] S3 us-east-2
- [ ] Orion/Hercules
- [ ] S4
- [ ] Discover
- [ ] Casper/Derecho
- [ ]  NOAA ParallelWorks Gcloud

**Comment by climbfuji** [comment]
All done.
